### ISSUE TITLE
Signed in timer initiation moment 

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#110]
I read a reply from @simonbaird elsewhere that one is signed/thrown out "after 5 hours" but it seems to happen more arbitrarily and here's a theory to why: Could it be that one is thrown out after a certain times has passed *from when one signs in* - as opposed to after e.g *last time one saved*?

If so, I propose to change the timer count from *the last saving moment* to reduce the seemingly arbitrary throw outs.

**Comment by simonbaird** [comment]
I would expect it's after 5 hours of inactivity, but there might be some other reason that a session is lost. Some investigation is needed to better understand what's happening.

One possibility is if the server restarts then sessions might be lost, but I'm not sure if that's true or not.

**Comment by simonbaird** [comment]
FYI I think just reloading your site is enough to restart the session timeout. You don't have to have a reload a https://tiddlyhost.com/  page.

**Comment by twMat** [comment]
>FYI I think just reloading your site is enough to restart the session timeout. You don't have to have a reload a https://tiddlyhost.com/ page.

Thanks but then one must not have any unsaved changes of course which, at least for me, is the typically situation. I only realize I'm logged out when I attempt to save and the "Starting to save" slide-in shows but then not the "Saved" slide-in... which, BTW, is *very* easy to miss.

If there is the "tiddlyhost plugin" as we discussed elsewhere (i.e for access to various TH stuff directly in the TW) then maybe it could overwrite the save button to send a refresh when saving so that one is re-loggedin before the saving? Just an idea.

**Comment by simonbaird** [comment]
Yeah I think that could work. A "smart" saver could throw up a login modal dialog when you need it, then proceed to save the site once you've authenticated.

**Comment by simonbaird** [comment]
This is pretty old now, so I think it can be closed. #173 is open to track the login modal idea. #262 is tangentially related.

Reading back, the situation where the "Saved" notification never shows up is indicative of Tiddlyhost being down or unresponsive. If it's just the session is timed out you should get the "If this is your site then login at..." message.
