### ISSUE TITLE
Save to web (TiddlySpot)

### ISSUE THREAD

**Issue by acarv** [simonbaird/tiddlyhost#111]
Not working on Classic from http://acarvalho.tiddlyspot.com/ .
It gets stuck on first message "About to upload on http://acarvalho.tiddlyspot.com/index.html ..."

**Comment by simonbaird** [comment]
I was attempting to reproduce the error, and it seemed to work for me. Did you enter your tiddlyspot site password under "options", or under "upload" in the backstage menu? What browser are you using? Is there an error message in the javascript console? (Use right click, inspect, console to access that.)

**Comment by acarv** [comment]
In the afternoon I was trying on Windows 10 and last version of Firefox.
I'm almost sure I tried both password inputs.
I have some browser plugins that may interfer and was also in a very
restricted VPN.

Now I tried in Windows 7 with Firefox 56 also with VPN but a much open
one and it worked.
Bet the problem is on my side. Thanks for the prompt response. If I
find the cause I'll add it to this issue.

Best regards
André

**Comment by simonbaird** [comment]
👍

**Comment by acarv** [comment]
Today is working even through Barracuda VPN... definitely something on this side...
Thank You and sorry for the trouble.

**Comment by simonbaird** [comment]
No worries, thanks for checking it.
