### ISSUE TITLE
JSON end point parameter for skinny tiddlers

### ISSUE THREAD

**Issue by saqimtiaz** [simonbaird/tiddlyhost#118]
> See also the tiddlers.json end point. Examples:
> 
> * https://simon.tiddlyhost.com/tiddlers.json
> * https://simon.tiddlyhost.com/tiddlers.json?pretty=1
> * https://simon.tiddlyhost.com/tiddlers.json?pretty=1&include_system=1

@simonbaird could we add a query string parameter to get the tiddlers in skinny form, that is without the text field? In some situations where all you want is the metadata for indexing, this will be even more efficient.

`&skinny=1`

_Originally posted by @saqimtiaz in https://github.com/simonbaird/tiddlyhost/issues/112#issuecomment-814017478_

**Comment by simonbaird** [comment]
Example:

* https://simon.tiddlyhost.com/tiddlers.json?skinny=1&pretty=1

**Comment by saqimtiaz** [comment]
@simonbaird excellent, thank you. This is prompting some nostalgia reminding me of r4tw from back in the day.
