### ISSUE TITLE
@kookma and @Jermolene should set their username ;)

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#120]
I'd like these urls to work:

* https://tiddlyhost.com/hub/user/kookma
* https://tiddlyhost.com/hub/user/Jermolene

Can be done via https://tiddlyhost.com/users/edit .

**Comment by simonbaird** [comment]
Attention @kookma

**Comment by simonbaird** [comment]
Also @jermolene

**Comment by simonbaird** [comment]
An example hub link for a user with a username:
* https://tiddlyhost.com/hub/user/MatVonTWaddle

**Comment by Jermolene** [comment]
Thanks @simonbaird I just tried to retrospectively add a username, but got this error when clicking "Update":

<img width="435" alt="image" src="https://user-images.githubusercontent.com/174761/113725670-71766e80-96eb-11eb-8c11-e13afa73783d.png">

**Comment by simonbaird** [comment]
You have to enter your current password down the bottom when updating user settings.

**Comment by simonbaird** [comment]
I've done that myself a few times... Filed #121 to fix the bad UX.

**Comment by kookma** [comment]
> I'd like this url to work:
> 
> * https://tiddlyhost.com/hub/user/kookma
> 
> Can be done via https://tiddlyhost.com/users/edit .

I will check right now!

**Comment by kookma** [comment]
> Attention @kookma

I was not at my desk! I will check now

**Comment by kookma** [comment]
> 'd like this url to work:
> 
> * https://tiddlyhost.com/hub/user/kookma
> 
> Can be done via https://tiddlyhost.com/users/edit .

Hi Simon,
 I opened the https://tiddlyhost.com/users/edit and fill out the form and now the link https://tiddlyhost.com/hub/user/kookma works for me!

Now when I click on https://tiddlyhost.com/hub/user/kookma it takes me directly to my home page on Tiddlyhost!

**Comment by simonbaird** [comment]
Sweet! Thanks very much.

**Comment by kookma** [comment]
More inputs:

- Clicking on https://tiddlyhost.com/hub/user/MatVonTWaddle shows the hub with sites created by Matias
- Clicking on a user avatar below a site on the hub shows the user details (avatar/picture and name and sites created by that user)

**Comment by Jermolene** [comment]
> You have to enter your current password down the bottom when updating user settings.

Thanks @simonbaird all well now

**Comment by simonbaird** [comment]
Lovely, thanks!
