### ISSUE TITLE
 "Plan must exist" error when trying to sign up

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#13]

**Comment by simonbaird** [comment]
Actually I can't reproduce it now, so maybe it's fixed already.

**Comment by morosanuae** [comment]
It seems to be fixed now. I've no longer encountered this error and I've manage to create my account successfully. Thanks!

**Comment by simonbaird** [comment]
Let's close.

**Comment by simonbaird** [comment]
#31 was the likely root cause here.
