### ISSUE TITLE
I never got the confirmation email, neither the "Resend confirmation instructions" email works

### ISSUE THREAD

**Issue by offray** [simonbaird/tiddlyhost#137]
Hi,

I'm teaching TiddlyWiki to my students (of Master Studies in Culture and Childhood) and I told them to use TIddlyHost to publish the wikis we have been working offline so far. One of them told me that the option of Upload sites is not being shown in her screen (see attached screen below). So I tried to replicate the procedure myself. But, again,  I didn't get any confirmation instructions or the resend confirmation email worked at all. I tried another email with the same behavior. We have already did another workshop with different participants and they managed to create their TiddlyHost accounts without any problem and, in fact, the guides I published for this new students cohort was using the documentation we created in the first workshop, where uploading wikis worked properly, as shown in [memories here](https://mutabit.com/repos.fossil/indieweb/uv/docs/es/miniwiki/indieweb-brea.html#TiddlyHost) at step 5 screenshots (they're in Spanish, but I have linked the screenshot for reference here also).

So comparing the two screenshots below, both should show the "Actions" button, isn't it?

I'm was an intense TiddlyWiki user in TiddlySpot ([personal site](http://offray.tiddlyspot.com/), [algebra lineal site](algebralineal.tiddlyspot.com)), coming back after a long hiatus of almost a decade. Now I host my own wiki/web sites, but I'm very thankful for TiddlySpot and now for TiddlyHost and I would like to continue showcasing it as a friendly site to host your personal wiki (digital garden/oasis) for my students and workshop participants. For that, having the possibility of using TiddlyHost first hand is important in order to give support to new learners.

Thanks for TiddlySpot all these years and for TiddlyHost now. 

![image](https://user-images.githubusercontent.com/5748170/115090613-ebbca500-9eda-11eb-8ab8-e4950e26d2ba.png)

![](https://docutopia.tupale.co/uploads/upload_edf7007056b65123283077ddb66c6b30.png)

**Comment by simonbaird** [comment]
1.  Re the upload button: Your student needs to firstly create a site, then they will be able to upload to it. There's no upload button until a site has been created.

2. Regarding your confirmation emails, it looks like they're being sent okay. Could they be landing in your spam folder? In any case, if you email me directly I'll try to get a confirmation link to you.

3. I see your old sites are broken without the jsMath library. I do have #123 open to look at fixing that. Do you think the current jsMath is compatible with the 2007/2008 jsMath? I'm wondering what version would be best for compatiblity with Tiddlyspot sites that use it. (Maybe post your answer on #123 if you have any ideas.)

4. We could also talk about making you the owner of your two old Tiddlyspot sites and also resetting the save password, but maybe it's better to deal with 2 & 3 first.

**Comment by offray** [comment]
Thanks a lot. Effectively my confirmation mail was lost inside the spam folder.

Regarding recovering the old sites. There is not any rush now. In fact, what I would like to do is to download the old sites and see how they fit in the new versions of TiddlyWiki. Let's talk about that in #123.

Cheers,
