### ISSUE TITLE
Is TH down? - 502 Bad Gateway

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#150]
It started around 7 hours ago. 

<:-)

**Comment by simonbaird** [comment]
Ooh, thanks. Will see what I can do.

**Comment by simonbaird** [comment]
Got a "cannot exec in a stopped state: unknown" from docker. Not sure what it means.

**Comment by simonbaird** [comment]
Restart fixed it...

No idea what happened or why, unfortunately. :/

**Comment by twMat** [comment]
>No idea what happened or why, unfortunately. :/

At least it works again. 

Thank you very much for taking care of it.
