### ISSUE TITLE
No confirmation e-mail received

### ISSUE THREAD

**Issue by ambiprospect** [simonbaird/tiddlyhost#156]
I am a TiddlyWiki user and would like to find a host for my blog "Think Global & Act Locally" online which feature Tiddlyhost seem to offer.

**Comment by simonbaird** [comment]
I can see the email, and it appears not to have bounced. The most common reason for confirmation emails not being received is that the confirmation email is being classified as spam. Did you check your spam folder?

**Comment by ambiprospect** [comment]
I am using Gmail and I have checked " All mail" which I believe will
contain also those mails Google regards as spam, but nothing from
Tiddlyhost.

Folke
<https://about.me/folkehs?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel>
Folke Hermansson Snickars
about.me/folkehs
<https://about.me/folkehs?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel>
Member of  Klimatsvaret <https://klimatsvaret.se/> - Citizens' Climate
Lobby - Sweden
Member of  Humanists Sweden <http://humanisterna.se/in-english/> and the
political platform INitiativet <https://initiativet.se/> (in Swedish) A
somewhat outdated presentation in English
<https://www.newyorker.com/news/our-columnists/the-invention-of-a-new-kind-of-political-party-in-sweden>
Wikipedia User:Ahi-nama <https://en.wikipedia.org/wiki/User:Ahi-nama>
Member of *Team Internet*
<https://www.internetmuseum.se/tidslinjen/internetmuseum-skriver-historia-pa-wikipedia/>
organized
by the Swedish Internet museum
<https://www.internetmuseum.se/tidslinjen/internetmuseum-skriver-historia-pa-wikipedia/>
(in
Swedish)
Member of the European Citizen Action Service <https://ecas.org/> and
the European
Buildung Network <https://www.europeanbildung.net/>
 Founding member of MyData Global and MyData Sweden <http://mydata.org>

@ahinama <https://twitter.com/ahinama>
Global linkblog: Think global, Act local <http://instantoutliner.com/c>
hermanssonsnickars/ <http://se.linkedin.com/in/hermanssonsnickars/>
T: +4615616068
M:+46707252840
Skype: snickars0156

**Comment by simonbaird** [comment]
I tried resending it from my personal gmail account. Check your email again now.

**Comment by simonbaird** [comment]
This one had a happy ending iirc. Closing the issue.
