### ISSUE TITLE
Allow users to delete their claimed Tiddlyspot sites

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#157]
It's a little easier now that we don't go looking in dreamhost for non-existing sites, (which would have meant that deleted sites would reappear again.)

But still it's probably better to mark them as deleted rather than nuke the record, so that it will be easier to clean up the dreamhost data later.

See also #140.

**Comment by shrysr** [comment]
+1 for the ability to delete old tiddlyspot sites. Thank you for putting this up as an issue.

**Comment by simonbaird** [comment]
Deleting is now available, as is redirecting to a Tiddlyhost site.
