### ISSUE TITLE
Error with Saving uploaded files 

### ISSUE THREAD

**Issue by kartikeyasri** [simonbaird/tiddlyhost#160]
Whenever I am trying to save the changes in the uploaded TW file it downloads the copy and doesn't save the file on the server. I am trying to use Tiddlyroam by uploading it.

**Comment by simonbaird** [comment]
If your Tiddlyroam is using 5.1.23 TiddlyWiki these extra steps are needed to make Tiddlyhost saving work.

**Comment by simonbaird** [comment]
Did that help?

**Comment by simonbaird** [comment]
I'll close this soon if there's no further update.
