### ISSUE TITLE
External images are no longer displayed

### ISSUE THREAD

**Issue by acarv** [simonbaird/tiddlyhost#165]
Tiddlyhost is not displaying external images from Dropbox.
I use a small macro to build the URL to the image and point to a Dropbox asset (https://acarvalho.tiddlyhost.com/#ImageMacro). 
The built URL works if called from the browser directly so I assume it is not a Dropbox problem.
It was working until recently...

Best regards
André

**Comment by simonbaird** [comment]
Is it still broken for you? I can see images there now.

**Comment by acarv** [comment]
Still can't see them here...
It seems to only affect images loaded through the macro at https://acarvalho.tiddlyhost.com/#ImageMacro the ones referring directly to an URL seem to work for instance at https://acarvalho.tiddlyhost.com/#SoftwareToolsPage .
It may have something to do with the fact that the macro also uses CSS to produce floating right and left...

**Comment by acarv** [comment]
Accessing from Windows 7 in another computer with an older Firefox seems to be working now.
I'll try again with the machine (its in a corporate VPN but that should not be a problem I think) that was failing tomorrow and will let You know.
Thanks anyway.
André

**Comment by acarv** [comment]
This was on my side : PrivacyBadger on new Firefox and Opera was blocking image download.
Sorry for disturbing You with this.
Best regards
André
