### ISSUE TITLE
User lapin uploaded my tiddlywiki

### ISSUE THREAD

**Issue by trumad** [simonbaird/tiddlyhost#166]
Hi! I made budgetlywiki, seen under my username:

https://tiddlyhost.com/hub/user/trumad

User lapin - https://tiddlyhost.com/hub/user/Lapin - has also uploaded budgetlywiki, but their version is older than my latest update. Would it be possible to remove or hide their version in the hub?

**Comment by simonbaird** [comment]
I appreciate your motivation, but I don't think I can do it.

Could you perhaps update the description to make it clear your site is the official distribution of BudgetlyWiki? Another idea: Add an "About" tiddler to your site to explain what it is and how to get started using it.

**Comment by trumad** [comment]
Ah, shame. I've added an [official] flag to the description.

I do have a small "help" link which helps explain how to use budgetlywiki. That seems to fulfill what you're suggesting? I am aware that it could do a better job of onboarding users in general. It's daunting on first encounter. I plan to make a video at some point.

**Comment by simonbaird** [comment]
FWIW I would suggest adding an "About" tiddler to the Default Tiddlers list. If a user clicks on https://budgetlywiki.tiddlyhost.com/ I think their immediate questions are "what is this?", "how does it work?", "who created it?", "how could I use it?". At the moment none of these are answered so it's a confusing experience. Also this would distinguish your site from Lapin's.

Secondly, I think something like this would be better for your description: "A personal budget calculator for TiddlyWiki. The offical source for the latest version of BudgetlyWiki, created by trumad."

**Comment by simonbaird** [comment]
Let's close the issue anyway.

**Comment by trumad** [comment]
Helpful feedback. Thanks Simon.
