### ISSUE TITLE
Tiddlywiki is not saving on tiddlyhost. Neither am I able to upload a TW5.

### ISSUE THREAD

**Issue by atulgrover** [simonbaird/tiddlyhost#167]

**Comment by simonbaird** [comment]
It's working for me now. Can you describe what happened? Did you get an error message?

**Comment by atulgrover** [comment]
It did not work for an hour or so… afterwards it started working again. I don’t know what happened. No error message. It said “STARTED TO SAVE WIKI” but never returned with the “WIKI SAVED” message.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by simonbaird** [comment]
I'm not sure what the problem was, but I think the issue can be closed now.
