### ISSUE TITLE
TW5 wiki was saved last night; I can't download it this morning - Site can't be reached!

### ISSUE THREAD

**Issue by SpyderRider** [simonbaird/tiddlyhost#168]
[https://smd-notelines2-notetaking.tiddlyhost.com](https://smd-notelines2-notetaking.tiddlyhost.com ) Site can't be reached error message this morning for a TW5 that was saved last night.   I am not sure what to do as I stupidly don't have a local copy.

**Comment by simonbaird** [comment]
I don't know what the problem was, but perhaps the server was down, or perhaps there was a networking issue. Is it working again now?

**Comment by SpyderRider** [comment]
No, Simon, the problem persists.   I thought it worked for a couple of hours yesterday, but by this morning, it did not work again.

**Comment by SpyderRider** [comment]
This may have been resolved.  It works today, but unfortunately, I lost a collection of tiddlers from this wiki before the failure.   I will report back in a few days.

**Comment by simonbaird** [comment]
I'm not sure what the problem was, but I think the issue can be closed now.
