### ISSUE TITLE
I can't save my editions

### ISSUE THREAD

**Issue by efenord** [simonbaird/tiddlyhost#169]
I can't save the editions I have done in my wiki: https://sanfrancisco2185.tiddlyhost.com

**Comment by simonbaird** [comment]
What happens when you click the save button?

**Comment by efenord** [comment]
I get the saving start message but never get the saving completed one. The save button keeps red and, if I leave the page, I lost the new info I added. I have tried a couple of times yesterday (Brazil time, utc-3).

Fernando Oliveira
+55(11)97503-0807

________________________________

**Comment by simonbaird** [comment]
I tested with a copy of your site and I was able to save okay with Chrome and with Firefox (on Fedora Linux). What is your browser and operating system?

**Comment by simonbaird** [comment]
One thing to check: Make sure you're signed in to https://tiddlyhost.com/ when you try to save.

**Comment by efenord** [comment]
Ok. I'll double check my signing status before try again. I am using Win10 with Opera Browser.

Tks.

Fernando Oliveira
+55(11)97503-0807

________________________________
De: Simon Baird ***@***.***>
Enviado: terça-feira, 22 de junho de 2021 10:41
Para: simonbaird/tiddlyhost
Cc: efenord; Author
Assunto: Re: [simonbaird/tiddlyhost] I can't save my editions (#169)


One thing to check: Make sure you're signed in to https://tiddlyhost.com/ when you try to save.

**Comment by simonbaird** [comment]
FYI I've never tested Tiddlyhost with Opera, but afaik it should work okay.

**Comment by efenord** [comment]
Hi Simon,

Just tried again and now it’s working fine. I am not sure what happened in the previous try as I haven’t done nothing different this time, but the important is I am able to save the changes.

 

Thanks for all the assistance. 😊

 

Fernando Oliveira

+55(11)97503-0807

 

De: Simon Baird ***@***.***> 
Enviada em: quarta-feira, 23 de junho de 2021 13:42
Para: simonbaird/tiddlyhost ***@***.***>
Cc: efenord ***@***.***>; Author ***@***.***>
Assunto: Re: [simonbaird/tiddlyhost] I can't save my editions (#169)

 

FYI I've never tested Tiddlyhost with Opera, but afaik it should work okay.

**Comment by simonbaird** [comment]
I'm not sure what the problem was, but I think the issue can be closed now.
