### ISSUE TITLE
I can't access the site

### ISSUE THREAD

**Issue by jsordan** [simonbaird/tiddlyhost#180]
angelshigh.tiddlyhost.com

I cant access this site and i made all my updates for the past days.

**Comment by simonbaird** [comment]
I'll take a look.

**Comment by jsordan** [comment]
Thank you Simon. 

That is our San Francisco itinerary and we are about to leave and the site just crashed and all our flight details are in there.

Thank you very much.

**Comment by simonbaird** [comment]
It's not looking good. For some reason the file is missing from the S3 bucket. I don't know why, and I've never seen it happen before. I might be able to recover an older version of your site from a backup, but the the data will be a week old.

**Comment by jsordan** [comment]
I just created the site several days back and backup might not have that.
 
I spent long nights and not sure if I can recreate it.

Can you please check the backup then?

Thanks for looking.

**Comment by simonbaird** [comment]
Is there a name or a unique-ish word or series of words likely to be found in your site that I could use to search?

**Comment by simonbaird** [comment]
Never mind, I think I have it. Good news! Give me a few minutes and I'll figure out the best way to get the site working again.

**Comment by jsordan** [comment]
Thank you thank you.  All about San Francisco trip.

**Comment by simonbaird** [comment]
Site should be back now.

**Comment by simonbaird** [comment]
It would be a good idea to download a backup (click https://angelshigh.tiddlyhost.com/download ) just in case whatever happened happens again.

**Comment by jsordan** [comment]
Thank you very much.  Just checked it to the airport.
