### ISSUE TITLE
Any support for mGSD?

### ISSUE THREAD

**Issue by Kikaider** [simonbaird/tiddlyhost#181]
Any chance TiddlyHost will support older [mGSD ](https://monkeygtd.blogspot.com/)TiddlyWikis? When I tried to upload an mGSD TiddlyWiki file I received the error "418 Invalid TiddlyWiki" when trying to open it.

**Comment by simonbaird** [comment]
It will work if you upgrade to a newer version of TW Classic.

See also #83.

Here's an (untested) step by step:

* Create a new site using "TiddlyWiki Classic". (Click "Advanced" to show the extra options when creating.)
* Download that new site.
* Open the downloaded empty and import every tiddler from your mGSD TiddlyWiki.
* Save and then upload it back to TiddlyHost.

**Comment by Kikaider** [comment]
While that step by step worked to import all the tiddlers from my old mGSD TiddlyWiki, it did not bring over the functionality of mGSD.

I copied the bulk of the raw html from my old mGSD.html file into a new TiddlyWiki Classic site I created and downloaded and uploaded the file to TiddlyHost and it seemed to display and function fine. The native [Save] link did not work, but there is a [Save to tiddlyhost] command buried in a menu that worked.

Essentially, I updated the "var version" line
from: var version = {title: "TiddlyWiki", major: 2, minor: 6, revision: 5, date: new Date("October 6, 2011"), extensions: {}};
to: var version = { title: "TiddlyWiki", major: 2, minor: 9, revision: 2, date: new Date("February 12, 2019"), extensions: {} };

I will test the functionality of this uploaded file, but you may close this issue. Thank you!

![Screenshot 2021-09-15 133450](https://user-images.githubusercontent.com/19256231/133482654-5c95a918-08fe-4398-948e-d5eab4e1dfe3.png)
