### ISSUE TITLE
[feature request] $:/status/IsLoggedIn set to yes when logged in

### ISSUE THREAD

**Issue by Telumire** [simonbaird/tiddlyhost#189]
Hi, since tiddlyhost does not use the password nor the pseudo in the TiddlySpot saver settings, $:/status/IsLoggedIn is missing even when logged in.

It would be handy to have this to be able to customize the wiki according to the current login status.

From the doc :

> The tiddler $:/status/IsLoggedIn reflects the current login status with the values "yes" or "no", and $:/status/UserName reflects the current username.

Relevant : 

- https://read-only.tiddlyhost.com/#Disable%20read-only%20if%20user%20is%20logged%20in
- https://tiddlywiki.com/#WidgetMessage%3A%20tm-login

**Comment by simonbaird** [comment]
I pushed a build with this today.

Try it out, e.g
* https://read-only.tiddlyhost.com/#%24%3A%2Fstatus%2FIsLoggedIn
* https://read-only.tiddlyhost.com/#%24%3A%2Fstatus%2FUserName

**Comment by simonbaird** [comment]
I didn't actually try to get a readonly mode working, but I assume it could be done.

**Comment by Telumire** [comment]
@simonbaird  Yes, this works perfectly : 
https://read-only.tiddlyhost.com/#Disable%20read-only%20if%20user%20is%20logged%20in

Thanks a lot !

**Comment by simonbaird** [comment]
Cool!
