### ISSUE TITLE
Saving or uploading doesn't work

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#196]
I have several wikis in TH that work well, including to save them.

But today I created another wiki via "Your sites", specifically the wiki https://scribble.tiddlyhost.com/ which I set as "Private".

I can create new tiddlers but clicking the Save wiki button doesn't save. For a workaround, I tried to instead download the wiki to my computer (that worked) and then, via "Your sites", use the "Actions > Upload" feature but this also fails.

**Comment by simonbaird** [comment]
Do you get an error message, or just silent failure?

**Comment by simonbaird** [comment]
I was able to create a new site and save it. Also upload works.

(But I did find a bug, perhaps new for ET 5.2.1.)

**Comment by twMat** [comment]
> Do you get an error message, or just silent failure?

First just a note: While now testing stuff in order to reply here, it seems a saving did get through but after several minutes loading in the background. 

BTW I'm on Win 10 and have now tried Brave and FF.

Regarding "Error message or silent":

For in-wiki saving the usual "Starting to save wiki" message but then no "Wiki saved" message.

For the "Upload to site ", after selecting the wiki to upload and confirming that I want to upload in the popup, the page keeps loading for a few minutes then "https://tiddlyhost.com/sites/3699/upload" and page reads 

```
Secure Connection Failed

An error occurred during a connection to tiddlyhost.com. PR_CONNECT_RESET_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…
```

**Comment by simonbaird** [comment]
Not sure if it's relevant, but I found https://support.mozilla.org/en-US/questions/1280856 re PR_CONNECT_RESET_ERROR.

It might be related to a size limit on the file upload that's enforced by your vpn.

**Comment by simonbaird** [comment]
Let's close this one, but I'm interested to hear if you find more about what caused it.

**Comment by twMat** [comment]
No more insights. Turning off the vpn solved it. But it now works as normal also with the vpn turned on.

**Comment by twMat** [comment]
@simonbaird 

New report of probably same problem:

New computer (Win 11, Brave browser) no VPN installed yet: I wanted to upgrade one of my TH wikis so used the usual procedure to download it from TH, shlepp it onto the official tw upgrade site, download. Then in Ctrlpanel under tiddlyspot tab, enter `https://xxx.tiddlyhost.com` ... click Save button... "Starting to save wiki"... but no "Saved wiki"

The upload feature via the "Your sites" page saved me, i.e it worked.

A red herring was that downloading the file from TH gave a html file. Upgrading it turned it into htm. ...but manually changing the latter into html and trying to use normal Save button didn't give any different result.

**Comment by simonbaird** [comment]
It sounds like you're expecting to be able to saving directly to Tiddlyhost from a `file://` url. AIUI that will never work due to brower security restrictions, though it was possible for a while back in 2006/2007.

**Comment by twMat** [comment]
>It sounds like you're expecting to be able to saving directly to Tiddlyhost from a file:// url. 

Right, for this last report I did attempt to upload from `file://`. But, OK, so that is not "supposed" to work. My initial error reporting in this thread did not refer to that though. Conclusion: disregard my post from this last 24 hours.
