### ISSUE TITLE
Feature request: Clone wiki

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#198]
Shortly after the noob stage, a TW user identifies "favourite plugins, settings and customizations" that he wants for all his wikis. I dare say this happens to *all* TW users. And those that go deeper into tiddlyverse probably develop fine tuned recurring setups (e.g *public* vs *private* wikis, *work* vs *non-work* etc). But to manually drag'n drop plugins + modified shadow tids and other tidbits is a rather annoying task. 

Therefore, I wonder if TH could feature a simple "Clone wiki" feature in the *Your sites* page. It could appear as a menu option in the "Actions" button and it can lead to the same page as the "Create site" button, i.e to register a new TH site, but instead of an empty wiki it is a clone.

Thoughts?

**Comment by simonbaird** [comment]
Yeah, I like this suggestion.

**Comment by saqimtiaz** [comment]
There is some slight overlap with the goal of #192 which is about being able to clone any TiddlyWiki by adding the appropriate query string to a TiddlyHost URL.

**Comment by simonbaird** [comment]
See also https://github.com/simonbaird/tiddlyhost/discussions/230#discussioncomment-3031681 .

**Comment by twMat** [comment]
Bump.

This would also be an appropriate feature for the Create New site. Either in the *Advanced* or as a step after the user clicks the "Create site" button, i.e to select one of the existing wikis that is then merely copied instead of an empty one being instated.

**Comment by simonbaird** [comment]
Yeah, I think the "clone from other site" could probably fit in with the new UI introduced in #233.

**Comment by simonbaird** [comment]
Actually I'm getting two different ideas mixed together here. Let's start with the simple clone option from the actions menu as originally suggested.

**Comment by simonbaird** [comment]
@twMat FYI I just pushed a build with the new "Clone" option in the action menu. Give it a try and let me know if you find any problems.

**Comment by simonbaird** [comment]
I called it "Clone" rather than "Duplicate". The clone option sends you to the create form where you can manually choose the name, rather than give it a name automatically like "copy-of-foo" or whatever. Note that only the content is cloned, the other settings you have to set manually before creating.

**Comment by twMat** [comment]
Wunderbar! I did a quick test and it seems to work as intended. I think you struck the perfect balance in the UI - the "Clone" as one of the Actions, which straight away sends the user to the create form, where it is again clear that one is creating a clone. Well done!

I think this is worth announcing somewhere, and a quick mention that this enables you to, for example, create empty "favourite setups".
