### ISSUE TITLE
Could Tiddlyhost serve Bob or other multi-user solution?

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#199]
Fellow @inmysocks created [Bob](https://github.com/OokTech/TW5-Bob) long ago and has refined it ever since. Among many other things, Bob features... *"Multi-User support for using/editing the same wiki(s) simultaneously"*

Multi-user collaboration would be a *tremendous* boon for TW development. The absolute majority of tiddlywikians are *not* developers and in my experience, this means they are *not* comfortable to use expert services like github (I'm myself certainly one such individual). But they do get skilled in wikitext merely from using TW and many can contribute a lot to the greater TW-good with e.g documentation etc - if there was just a convenient way to do so.

I believe Tiddlyhost is the most convenient and direct way to "get a wiki out there" so I'm wondering if it is possible to include Bob as an option for wikis? If not, could multi-user collaboration be achieved via Tiddlyhost in any other way?

I'm posting the [mirrored question](https://github.com/OokTech/TW5-Bob/issues/186) on Bob's github.

Thank you.

**Comment by twMat** [comment]
OK, @inmysocks posted a reply in his ghithub:

>If tiddlyhost works similarly to how tiddlyspot did Bob wouldn't work on it. Bob has a dedicated server component. Eventually I will get the secure server part finished in a way that is easy for other people to set up and then it could be a similar thing, but I don't think Bob will play well with tiddlyhost.

So, is Jeds hunch correct and it wouldn't work?

**Comment by simonbaird** [comment]
I like the idea of a multi-user Tiddlyhost, but I don't think it's going to happen any time soon.

**Comment by twMat** [comment]
thanks for reply.

**Comment by AKmatiAK** [comment]
So it's not going to happen? I also want to use Bob wiki, but it doesn't work with my hosting.

**Comment by simonbaird** [comment]
Not this year or next year, but maybe someday.
