### ISSUE TITLE
Downloaded file is unusable.

### ISSUE THREAD

**Issue by rexfrancis** [simonbaird/tiddlyhost#200]
Formatting is weird and saving doesn't seem to work anymore.

**Comment by simonbaird** [comment]
Will close this soon if there's no further updates.

**Comment by rexfrancis** [comment]
I'll be honest I game up on it 2 weeks ago and figured out a different
hosting solution. I'm happy to send you the corrupted file if that would
help you troubleshoot.

**Comment by simonbaird** [comment]
Can you tell me the site name with the problem?

**Comment by rexfrancis** [comment]
Sorry to say I pulled it all down and closed my account.
