### ISSUE TITLE
Signup username says "optional" but isn't

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#204]
Setting up a new account for my daughter and I intended to leave the "username" field empty. It says "optional" in its description. I didn't make multiple tests with new accounts so I might have misunderstood something. Maybe the empty username is already taken, so to say?

The reason for wanting to leave it empty is another issue that I've wanted to report about for a long time but will mention briefly since I'm at it: Having a username apparently auto-inserts it in the username field in Gettingstarted/Ctrlpanel which makes it appear in all tiddlers subtitles. Even after removing the username, it get's reinserted when the wiki is reloaded. This makes tiddlersubtitles in my private wikis show the typical blue username modifier link in every tiddler, which is distracting.

**Comment by simonbaird** [comment]
I think it's related to the brower's autofill behavior. I'm pretty sure you can leave it blank, but your browser might try to autofill a value for you.

There might be a way to avoid that, but I'm not sure. Some investigation needed.

**Comment by twMat** [comment]
I take it your reply refers to my second paragraph about the user name being filled in automatically in the wiki (as opposed to my first paragraph that deals with the registration process).

It seems unlikely to mee that the browser would automatically fill in the user name, especially when the Controlpanel (i.e that holds the username fileld) is not open. But are you saying that it is not a *feature* from TH? To "auto-add" the username on load, so it appears by default when new tiddlers are created or modified?

**Comment by simonbaird** [comment]
No, that's not a feature of TH. Browser autofill only.

I guess it's a feature idea, but I don't think I'd want to impose that choice of username in TW content.

**Comment by twMat** [comment]
OK, interesting. 

>I guess it's a feature idea, but I don't think I'd want to impose that choice of username in TW content.

I can see how it'd be useful in a multi-user context but for single user wikis it is only annoying.

<hr>

Just so it is not missed: The actual issue in the OP was just a report that it seems the sign up process requires a username even if it says it is optional. 

OK, not much more to add.

**Comment by simonbaird** [comment]
Oh, you're correct about the blank username being disallowed. That is indeed a bug. Thanks!

With a blank username, it shows this:
```
1 error prohibited this user from being saved:
Username has already been taken
```

**Comment by simonbaird** [comment]
This should be fixed now, but I'll create another issue to consider how the username field impacts TiddlyWikis with the autofill. At the very least it could be documented and maybe included in the FAQ.

**Comment by twMat** [comment]
Thank you Simon
