### ISSUE TITLE
No Confirmation Email

### ISSUE THREAD

**Issue by wwjimd** [simonbaird/tiddlyhost#212]
Hi, 

In attempting to sign up for an account, I never received a confirmation email. I've tried resending twice to no avail. Not sure what next steps would be.

My email address is: wwjimd@gmail.com
Username: wwjimd

Thanks,
Zach

**Comment by simonbaird** [comment]
I can see that it's being sent. Perhaps it's landing in your spam folder? The from address is `Tiddlyhost <tiddlyhost@gmail.com>` and the subject is "Confirmation instructions".

Anyway, I'll try forwarding you the link from my personal email.
