### ISSUE TITLE
Allow accessing a private wiki with API key or similar mechanism  

### ISSUE THREAD

**Issue by GameDungeon** [simonbaird/tiddlyhost#223]
The plugin tiddlyremember allows users to sync anki with tiddlywiki. The issue is with a private wiki tiddlyremember's request is rejected do not being logged in. Could you add a way to allow requests like this through?

**Comment by simonbaird** [comment]
I think it's a good suggestion. I like the idea of being able to create a token, perhaps with an expiration date, to allow either write permission, or view access to a private site.

**Comment by simonbaird** [comment]
FWIW https://github.com/simonbaird/tiddlyhost/blob/main/examples/thost-downloader shows how to script the current Tiddlyhost authentication.

**Comment by simonbaird** [comment]
Somewhat related to #72 in that the token creation could be the same.

**Comment by simonbaird** [comment]
I want to close this since it's just about identical to #246. For your use case, you just need view only access, right?
