### ISSUE TITLE
make rails-init failded： Your Ruby version is 3.1.2, but your Gemfile specified 3.1.1

### ISSUE THREAD

**Issue by shikihane** [simonbaird/tiddlyhost#224]
I run commond "make rails-init failded" then obtain error 18 "Your Ruby version is 3.1.2, but your Gemfile specified 3.1.1".
I am not acquainted with ruby toolchain.
What should I do ?

**Comment by simonbaird** [comment]
Thanks very much for the bug report. It should be fixed now, but you need to `git pull` the latest changes from main branch.

The reason for the bug is that the base "ruby:3.1" image in docker.io was updated to ruby 3.1.2 but the Gemfile was still specifying ruby 3.1.1.

**Comment by simonbaird** [comment]
See 10ce08e45ad30b15e73ff14a574ed2e4e2253bbf .
