### ISSUE TITLE
License ambiguity: All Rights Reserved

### ISSUE THREAD

**Issue by willwray** [simonbaird/tiddlyhost#235]
Firstly, apologies for bringing this up!
(I'm a open source proponent, not a lawyer, and don't grok most license discussions.)

The LICENSE.md file starts with

    Copyright (c) 2021-2022, Simon Baird.
    
    All rights reserved.

Err, ARR...
"All rights reserved" sounds, to me, contradictory to likely intent.
So I searched to see what the legal meaning might be.
Here's a link to, and a quotes from, an answer to a similar question: 

[MIT license and "All rights reserved."?](https://opensource.stackexchange.com/questions/2121/mit-license-and-all-rights-reserved)

>All rights reserved is a historic relic that is not relevant today for establishing copyright (the ownership part). In terms of licensing, it is detrimental to modern software licensing. The phrase has very specific, absolute meaning in the English language and can open up ambiguity in software licensing if it contradicts the rest of a license.

Please clarify intent.

**Comment by simonbaird** [comment]
It's meant to be a standard BSD license, see https://en.wikipedia.org/wiki/BSD_licenses . Looking now I can see that the resembles the "three clause" version which does omit the "All rights reserved", so I suppose there's no harm in removing it.
