### ISSUE TITLE
Add Target option to tiddlyhosts links "Your sites"

### ISSUE THREAD

**Issue by AnthonyMuscio** [simonbaird/tiddlyhost#241]
If we click on one of our listed sites it will always open in a new window, the link is likely to contain a target of "_blank".
* This means it is quite easy to open the same wiki in a different window and possibly overwrite changes from another tab.

Possible solutions
* On the setting for each site allow the owner to set a target name that will be used in the link
* The better and automatic solution is to set the target to the site name target="mysite.tiddlyhost.com"
  * A preset target can always be overridden with a "r-click open in new..." on the link

**Comment by simonbaird** [comment]
Great idea, thanks! Done.

I went for the  `target="mysite.tiddlyhost.com"` suggestion for everyone, rather than making in configurable. I can't see a good reason anyone would want to preserve the previous behavior.
