### ISSUE TITLE
 Frequently notice that Uncaught TypeError: Cannot read properties of null (reading 'offsetLeft')

### ISSUE THREAD

**Issue by wyLeon** [simonbaird/tiddlyhost#243]
"TypeError: Cannot read properties of null (reading 'offsetLeft')"  after using TiddlyWiki through the link generated from my Tiddlyhost sites.

![Uploading issue capture.png…]()

**Comment by wyLeon** [comment]
The alert showing again after I dragging the plugins from my old TiddlyWiki, I'm not sure if it's the conflict between the plugin and the core?
the url is&nbsp;https://leonwiki.tiddlyhost.com/


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "王煜"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月6日(星期二) 上午9:16
***@***.***&gt;;

主题:&nbsp;回复： [simonbaird/tiddlyhost]  Frequently notice that Uncaught TypeError: Cannot read properties of null (reading 'offsetLeft') (Issue #243)



Thanks a lot for your reply, it seems some problems occur in the local html file, because I've tried updated Chrome and Miscrofost Edge on 3 devices but the alert always popping out.


After exporting all non-systematic tiddlers to a blank template, the notification disappears till now.


Following the shortcuts of console for attchment. Thank you.


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "simonbaird/tiddlyhost"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月6日(星期二) 凌晨0:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [simonbaird/tiddlyhost]  Frequently notice that Uncaught TypeError: Cannot read properties of null (reading 'offsetLeft') (Issue #243)





 
Thanks for the report. I haven't seen this myself, but it sounds like a javascript issue. What url are you on when you get the error?
 
That screenshot isn't working. Could you have another try at putting the image somewhere? Or maybe you could email it to me. What browser are you using?

**Comment by simonbaird** [comment]
Since it's probably related to your TiddlyWiki and its plugins, I can't do much to help. If your still having problems, maybe you could post on the TiddlyWiki forum to ask for help, see https://talk.tiddlywiki.org/ .
