### ISSUE TITLE
Integrate hub with links.tiddlywiki.org

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#247]
Dear @simonbaird and @Jermolene (do `@` echo outside of this organization? Probably not.)

https://links.tiddlywiki.org/ is of course the tiddly communitys official collection of links to various TW resources. 

I think it would be mutually beneficial if *links* could automatically aggregate hub listed wikis from TH: It would very much lower the threshold to contribute there *and* it would encourage joining TH.

Thoughts?

A related note about the announced payment plans for TH: One idea could be that hub listed wikis on TH are outside of the payment scheme (i.e free) since they contribute to the TW project, but any private sites are part of the payment plan.

**Comment by simonbaird** [comment]
Do you mean every site listed on Tiddlyhost Hub becomes a link? Or do you mean hub listed sites containing links could be somehow discovered and have their links appear automatically in links.tw.org?

If the former, then I don't think it's a good idea, since there's a lot of uninteresting content there.

**Comment by simonbaird** [comment]
For the latter, perhaps a tag could be used for the discovery, e.g. slurp from all sites with this tag, https://tiddlyhost.com/hub/tag/links.tiddlywiki.com , but honestly I don't think it's high value.

I might be wrong, but I expect the set of people who: 1. care about links.tw.org and 2. want to to contribute to links.tw.org and 3. would do so if only there was an easier way, would be quite small.

**Comment by twMat** [comment]
Hm, having pondered and looked closer at the hub sites again, I think (both of) your conclusions about my OP are right. But I do believe the OP is on to something, it is just premature so I'll lay the OP to rest at this time.

However, your observations about the many irrelevant hub sites show another problem - and I think I figured out a reason for this! I'm closing this thread and starting #248 

Thanks.
