### ISSUE TITLE
Modify the "Create site" form for better hub site quality

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#248]
@simonbaird observes in #247 that many hub listed sites are of low general interest. I agree and believe this proposal can mitigate it even if the problem obviously can't be totally prevented:

For the creation of a new wiki, the radio buttons `Private` vs `Hub listed` imply that *"If I don't want it private then it has to be hub listed!"*  I would think this contributes to irrelevant hub listings. It is not self evident that checking *neither* of the buttons is a third alternative, and it is also not obvious what checking neither means. And, actually, if one does check an option then there is no way to uncheck both! Instead I propose:

**radio buttons** - and their explanations:
[X] Private - Make the site private, rather than publicly viewable. `default`
[O] Public - Make the site publicly viewable
[O] Public and hub listed - Include this site in the [Tiddlyhost Hub](https://tiddlyhost.com/hub) gallery.

**tags**:
AFAICT, for *private* and (merely) *public* wikis, tags don't contribute anything beyond what the *description* does, as seen in the Your sites listing. I.e tags are redundant.

However, the tags are very useful for the categorization of *hub listed wikis*, so this should be made clear. So during the New site creation, the tags field should *only* appear if the user checks the *Public and hub listed* option!  And the *tags* hint should mention that tags are used for automatic categorization of *hub listed* sites.

**Comment by simonbaird** [comment]
I like it.

**Comment by twMat** [comment]
Nice!

1) As for making Feather wiki more prominent; good idea, but/and I'd think that this is the first time many people hear about it. So just maybe the "info texts" about it should contain a *link* to it's main site? (...and the, for symmetry, I guess there should also be one for TW.) I.e:<br><br>`<a ...>`Featherwiki`</a>` is a new, modern, light-weight single-page wiki with Markdown and WYSIWYG support

2) ...and, spekaing of Feather, the https://tiddlyhost.com/ page, when one is not logged in, only mentions TW.

3) Possibly relevant for the "questionmark tooltip popups": Is there a difference in "search engine findability" for a Public vs a Hublisted wiki? I'm guessing "no" but if there is, then I guess some would like to know, and maybe the tooltip popup is a reasonable place to mention it.

Apropos this page, I just posted in [#198](https://github.com/simonbaird/tiddlyhost/issues/198#issuecomment-1307734629)

**Comment by simonbaird** [comment]
1. There is a link for each of them, but it's inside the tooltip content, so you need to click that ? icon to find it. Maybe it's better to have it in the main text, I'll give it some thought. It's kind of a trade-off between "enough info" and "too much clutter".
2. Good point, I'll aim to add it soon.
3. Not sure actually, I think it probably depends on whether there are links on the internet that a crawler can follow. But I'd expect that being hub-listed increases the chance of being indexed.

**Comment by twMat** [comment]
> There is a link for each of them, but it's inside the tooltip content,

Ah, silly of me to miss it considering I did note the later tooltips. (But then, actually, maybe all of the text for the two wiki options should be inside the tooltip? The info is kind of repeated as it is now. Just a thought.)
