### ISSUE TITLE
TH as a central hub/library

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#25]
Simon, if this is too much off topic, just close it right away. No need to explain.

The need for a central hub for e.g plugin distribution is greater than ever after TS shut down. Could TH somehow have a "front" where all wikis that are somehow marked as "plugins" and other categories, appear? I.e they appear as links to their respective wiki.

It would be ideal if any user could add meta data to the listed instances on that front site, e.g to categorize the wiki(link), and maybe give reviews etc. (I have further thoghts on this, if it is of interest).

See also [User stories for a community plugin library #5399](https://github.com/Jermolene/TiddlyWiki5/discussions/5399) for relevant aspects.

**Comment by simonbaird** [comment]
This is a great idea, and not too hard to implement.

I'm wondering if we should have a fixed set of categories, or let there be a freeform set of tags?

Maybe we need another field for "searchable", since you could have a public site that you don't want to appear in lists.

**Comment by kookma** [comment]
> I'm wondering if we should have a fixed set of categories,

Yes, please have a set of categories! These categories can be revised or extended based on user feedback. Have no limitation makes a lengthy list with redundant tags. There is a bad experience on free tagging in TW Google Forum

**Comment by twMat** [comment]
>I'm wondering if we should have a fixed set of categories, or let there be a freeform tag list, and "plugin" (or "tw-plugin", or "TiddlyWikiPlugin") is just one of those tags?

So this is exactly the issue I have thoughts about:

IMO the optimal solution would be freeform tags so any (registered?) user can add any number of tags. But users can also *vote* on existing tags (with "+1/-1" or "like/dislike"), so that they are all ordered by how "fitting" they are according to consensus. This way, it is positive with plenty of tags and perhaps only the, say, "top 3" of them are directly visible, and there's a little ellipsis or something show the rest.

A users vote persists until he changes it. I.e clicking "+1" again will just reset the vote to neutral, not add yet one more up vote.

There could also be a vote for "remove this tag" and once it hits a threshold, the tag disappears. This should eliminate conflicting tags ("TiddlyWikiPlugin" vs "tw-plugin") as well as the occasional misuse. A threshold value could be, say, "n% of total number of votes but with a minimum of m".

These tags are what forms the categories (meaning one plugin can appear in multiple categories).

...

I also have other ideas for promoting quality plugins, if there's interest.

**Comment by simonbaird** [comment]
The ranking of sites or tags according to their +1/like count is interesting, but I think it's something for later. I want to focus on the primary function, i.e. a convenient hosting service for TiddlyWikis.

Another idea: Plugins are code, so their main "home" should be Github. What if Tiddlyhost could generate a TiddlyWiki plugin site from a particular github repo? It would start with an "empty" file, inject some tiddlers fetched from github, and serve it up as a TiddlyHost site. These type of sites would be read only, since they're generated from Github.

**Comment by DanielBaird** [comment]
I've previously used bag'o'tags that users can put whatever they like into, and then some of those get blessed as ""categories"" and have category pages made, etc.
So users can choose what they like, but if they want to get onto the Plugins category, they have to use `tw-plugins`. And if a category becomes popular in the community, like Dungeons and Dragons gets popular using `dnd` and `d&d` tags, the site runners can choose to bless whatever the most useful community tag is as the category defining one, and viola there's already a fair bit of content for this new category.

**Comment by simonbaird** [comment]
Yeah, I also like to keep it loose as far as tag taxonomies go.

This is WIP and a little undercooked, but take a look:
https://tiddlyhost.com/hub

Code is in #30 .

**Comment by twMat** [comment]
>Another idea: Plugins are code, so their main "home" should be Github. What if Tiddlyhost could generate a TiddlyWiki plugin site from a particular github repo? It would start with an "empty" file, inject some tiddlers fetched from github, and serve it up as a TiddlyHost site. 

Excellent! But when you say "generate from a **particular** gh repo" do you mean peoples own repos or would they have to add it to a common one provided by you? 

And *who* would have to provide the gh link to TH - the creator or anyone referring to that gh repo? (hopefully the latter).

>These type of sites would be read only, since they're generated from Github.

...and the link to the repo could appear in the TW Controlpanel TH-saver tiddler. Or maybe it should be more prominent and directly accessible e.g a static link in the TW topmenu, perhaps as a gh icon.

**Comment by simonbaird** [comment]
https://tiddlyhost.com/hub is kinda functional now, so maybe we can close this soon. I'll review the discussion and see if we can extract any incomplete feature ideas into their own separate issues.

**Comment by simonbaird** [comment]
Added clickable usernames in 0.0.4. I think we can close this and create new issues for any future hub related feature ideas.

FYI:
* I took out the special "blessed" tags for plugins and docs. They might come back later, but for now we'll keep it organic.
* Upvotes/likes are trackedin in #59.

**Comment by simonbaird** [comment]
Thanks @twMat for the nice idea!
