### ISSUE TITLE
oEmbed / OpenGraph tags ?

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#250]
On talk.tiddlywiki.com I was going to post a link to a TH wiki by inserting the url on a separate row. There's some board feature that apparently fetches data from the linked to site but for my attempt I got this:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/4534056/194725561-bb9a54c7-2e67-48d7-b8bb-0dec9a647e49.png">

Considering that it is used on talk.tiddlywiki.com , is this something that could be resolved from TiddlyHost? Or is it something about the very wiki being fetched?

**Comment by simonbaird** [comment]
Looks like the solution involves adding some meta tags, something like this:

```
<meta property="og:title" content="Colby Fayock - A UX Designer &amp; Front-end Developer Blog" />
<meta property="og:type" content="website" />
<meta property="og:image" content="/static/website-social-card-44070c4a901df708aa1563ac4bbe595a.jpg" />
<meta property="og:url" content="https://www.colbyfayock.com" />
```

(Example via https://www.freecodecamp.org/news/what-is-open-graph-and-how-can-i-use-it-for-my-website/ .)

The idea of having Tiddlyhost inject those is interesting, and I think reasonably easy to achieve.

I think you could also add them yourself using TiddlyWiki's own mechanism for adding content to the head tag, which is to use the `$:/tags/RawMarkup` tag. Let me see if I can do it.

**Comment by twMat** [comment]
OK, so in the end it is a wiki-local matter and not a server matter, good to know. As you propose though, to have Tiddlyhost inject it is probably a good idea so that arbitrary "talk" forum users can link to arbitrary TH hosted wikis.

Thank you

**Comment by simonbaird** [comment]
Here's an experiment to demonstrate how you can do it:

* https://simon.tiddlyhost.com/#OpenGraph%20Tags%20Test
* https://www.opengraph.xyz/url/https%3A%2F%2Fsimon.tiddlyhost.com

Obviously the thumbnail image would be a better choice, but currently the thumbnail url changes everytime the site is saved. I'll make a new issue to suggest a static url for public site thumbnails.

**Comment by simonbaird** [comment]
I've implemented #251 - there's now a static url for thumbnails, e.g. https://tiddlygoo.tiddlyhost.com/thumb.png . It's a little low-res, but you can use it for opengraph image. See https://www.opengraph.xyz/url/https%3A%2F%2Fsimon.tiddlyhost.com which now uses that.

**Comment by twMat** [comment]
For the record, I've posted an issue on this in the TW repo: [link](https://github.com/TiddlyWiki/TiddlyWiki5/issues/8433)

**Comment by simonbaird** [comment]
This is coming soon in the next TW release. I'd still like to to #255, but this can close I think.
