### ISSUE TITLE
Provide a stable url for public site thumbnail images

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#251]
It would be useful for open graph tags, see #250 .

**Comment by twMat** [comment]
@simonbaird 

Hm, is $:/favicon.ico not sufficient for this? ([docs](https://tiddlywiki.com/prerelease/#Setting%20a%20favicon)) 

...and, as fallback, either the TH logo or the TW default favicon?

**Comment by simonbaird** [comment]
Example: https://simon.tiddlyhost.com/thumb.png

**Comment by simonbaird** [comment]
Not sure what you mean re favicon. Do you mean to extract the favicon image and use it or them opengraph image? That's a reasonable idea for #252 but I was thinking the thumbnail image that looks like the site would be better. Of course if you're doing your own opengraph tags you can use whatever image you like.

**Comment by twMat** [comment]
Sorry, yes I did mean extracting the favicon. But sure a thumbnail depicting the actual site is of course also an approach :)
