### ISSUE TITLE
Suggestions For Tiddlyhost

### ISSUE THREAD

**Issue by purplehazexxx** [simonbaird/tiddlyhost#259]
Respected Sir,

I am very grateful and inspired from your innovations, so I want to thank you for that first.

Knowing about tiddly-host thrilled me, as now I could now host my tiddly book online without any pain. I have some suggestions that I think would make tiddly ecosystem more robust and go to choice for aspiring bloggers like myself. 

Suggestions are 
1. Custom Domain - The inability to get a custom domain limits the prospects of using tiddly-host as my permanent platform for blogging. 
2. Doubts about stability - There are doubts about the stability of tiddly-wiki and tiddly-host, hence we are not sure how far we can go with tiddly ecosystem.
3. Pricing in Future - About pricing for your services, I am a student, and I am sure many like me use tiddly as it is free. I request you to keep in mind people like us while planning the pricing of Plans.  I think $5 or so is bearable for hosting the blog along with custom domain. 
4. AdSense  - Please allow Google AdSense for tiddly, that will make it a perfect choice for blogging. 

Thank You

**Comment by simonbaird** [comment]
Hi, thanks for the feedback. I'm glad to hear you're enjoying Tiddlyhost. Responses to your suggestions:

1. I like this idea a lot and there's an issue open for it, see #145 . As yet I haven't thought much about how to implement it, but it's definitely on the roadmap.

2. I'm aiming to make Tiddlyhost stable enough and reliable enough to be a useful and valuable service. As for TiddlyWiki itself, well it's not in my control, but it has been around for a long time and remains pretty healthy. I think you be confident about it.

3. Okay, thanks for the feedback.

4. I haven't thought about Adsense and Tiddlyhost much. I don't have any plans to do anything with it currently, but perhaps it could be possible.
