### ISSUE TITLE
Tagging with $:/tags/RawMarkup, brokes publishing to Tiddlyhost

### ISSUE THREAD

**Issue by leoperbo** [simonbaird/tiddlyhost#264]
I have a tiddler tagged with system tag $:/tags/RawMarkup, it's needed for distributed verification using rel="me" attribute.

I can save to Tiddlyspot and view my Tiddlywiki, but I can't do the same when saving to Tiddlyhost, there, when I try to view my TW published, Tiddlyhost shows:

> 418 Invalid TiddlyWiki
>
>This site does not appear to be a valid TiddlyWiki.

**Comment by simonbaird** [comment]
Thanks for the report. I'll take a look and see if I can figure out why it's happening.

**Comment by simonbaird** [comment]
I think your problem is mostly likely due to an unclosed tag or some other type of invalid html in the raw markup content. That can cause problems for Tiddlyhost even though the TiddlyWiki will render okay.

Double check that you have valid html with all elements closed, e.g. if you have a `<div>` make sure there's a matching `</div>` in the right place and any other tags in between are all nested in the right order.

**Comment by leoperbo** [comment]
I had double checked the code, it's ok. In deed, it works for distributed verification in: https://leoperbo.tiddlyspot.com/

When I upload exactly the same TW file to https://leoperbo.tiddlyhost.com/ is when Tiddlyhost shows the error message.

Same rel="me" code is working in the FeatherWiki that I finally uploaded to https://leoperbo.tiddlyhost.com/

Thank you for take a look.

**Comment by simonbaird** [comment]
From the source of https://leoperbo.tiddlyspot.com/
```
<div align="center" style=color:lightgrey>
TiddlyBlog es una bitácora no lineal creada por <a rel="me" href="https://mstdn.mx/@leoperbo" style="color:lightgrey">@leoperbo</a>
<hr color=lightgrey />
<br>
```

Try changing it to this:
```
<div align="center" style=color:lightgrey>
TiddlyBlog es una bitácora no lineal creada por <a rel="me" href="https://mstdn.mx/@leoperbo" style="color:lightgrey">@leoperbo</a>
<hr color=lightgrey />
</div>
```

**Comment by simonbaird** [comment]
This content ends up inside the <head> element, so I think actually a link tag is more appropriate. 

I would recommend replacing the whole thing with this:
```
<link rel="me" href="https://mstdn.mx/@leoperbo">
```

**Comment by leoperbo** [comment]
Thank you for checking up.

The lack of </div> was the problem... Triple check was necessary, shame on me .__.

Now, the main reason of insert rel="me" code into my TiddlyWiki was for auto-verification between my profile in Mastodon and my TiddlyBlog (on TiddlyHost). This will not work in Mastodon because it doesn't check rel="me" code in pages larger than 1 MiB, so, I created a "TiddlyCard" with FeatherWiki, and it works like a charm... The weird thing is that my original code, without de </div>, works in FeatherWiki and uploads flawlessly to TiddlyHost:

https://leoperbo.tiddlyhost.com

 
![Screenshot_20230114_094607](https://user-images.githubusercontent.com/13077338/212480496-11cd9069-57a2-4472-a4c6-be9a88bac7ef.png)

**Comment by simonbaird** [comment]
Okay, cool.

FWIW, I think an "external core" TiddlyWiki would be small enough to be under Mastodon's 1MB site threshold.
