### ISSUE TITLE
Allow hub sites to be designated as "cloneable"

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#266]
* If you (as site owner) want to make your site cloneable by others, list it in a the hub and configure it with a "make cloneable" option.
* Other signed in users, when browsing the hub will now see a clone button on that cloneable site. Also there would be a hub filter option to show only cloneable sites.

**Comment by twMat** [comment]
I like.

Any thoughts on what should happen when the close button is clicked? Specifically, I'm thinking it would be neat if the user was presented (modal?) with two alternatives: a field to fill in a non-existing Tiddlyhost name so to create a new site - or - show a list of the users sites (perhaps in a revealwidget?) so one can be selected for overwriting.

**Comment by simonbaird** [comment]
I'm thinking it would take you to the same form as it does for the existing clone function. What's the use case for replacing an existing site when cloning?

**Comment by twMat** [comment]
OK maybe that would be overkill. I was thinking that the user might first have first created the site only to then "fill" it with the solution he wants. This would also allow for a user to try out several solutions by overwriting easily it with a new one if desired. But, perhaps overkill.

**Comment by AnthonyMuscio** [comment]
Thanks Simon this sounds like a good approach. One thought when building this is can we make it possible for the source wiki to publish a button to "clone to my repository", ideally using the same mechanism to keep it simple. The equivalent of a download button.

 I thought this could be a premium feature but on reflection less barrier to new users, and shared editions the better.

**Comment by simonbaird** [comment]
I pushed this up to prod just now. If you want to try sharing a "template", which is what I'm calling a site that is configured as publicly cloneable, you can check the box under advanced settings.

If you want to browse the available templates, go to https://tiddlyhost.com/hub?t=1 .

One thing that could become a problem if is we get a lot of low quality, spammy templates showing up, but let's cross that bridge when we come to it.

**Comment by simonbaird** [comment]
> make it possible for the source wiki to publish a button to "clone to my repository"

Linking to: `https://tiddlyhost.com/sites/new?clone=sitename` will do it.

**Comment by simonbaird** [comment]
Done, mostly in 8b449cb5 but there are some related tweaks after that.
