### ISSUE TITLE
Idea: Run in safe mode in settings

### ISSUE THREAD

**Issue by michalradacz** [simonbaird/tiddlyhost#268]
Yes, running in safe mode is as easy as alternating URL, but in some cases isnt edit URL ideal (for example I have TiddlyHost as web-app without URL address bar), and this little feature can be usefull for some non-geek users :-)

**Comment by simonbaird** [comment]
That's a great idea, thanks! Consider it done.

**Comment by simonbaird** [comment]
You can find the safe mode links for TW5 and for Classic in the "Actions" menu for each site.
