### ISSUE TITLE
locked into "The site has been updated since you first loaded it. Saving now would cause those updates to be overwritten."

### ISSUE THREAD

**Issue by nuvema572** [simonbaird/tiddlyhost#271]
![image](https://user-images.githubusercontent.com/77842497/202917740-55fe12fe-880f-4519-9284-8ada2e272b0e.png)
consistently getting this error on firefox when trying to update or save, regardless of whether or not i've made successful changes on another browser. cache/cookie/etc. clear did nothing.
i have reloaded and reapplied the changes like it's told me to multiple times, deleted the offending tiddler on another browser (and saved successfully), and backed up my site without a problem.
if there's a way to 'force save' or overwrite the file that's on the server, please let me know.

**Comment by nuvema572** [comment]
used the method explained [here](https://github.com/simonbaird/tiddlyhost/wiki/About-the-two-different-save-methods) and fixed it, my apologies!

**Comment by simonbaird** [comment]
I'd like to figure the root cause here. Could you share what version of Firefox and what operating system you're using?
