### ISSUE TITLE
TiddlySPOT - how do I delete wikis?

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#276]
Hope it's OK I post this here;

I'd like to permanently delete some tiddly**spots**. I've visited them so they will not automatically disappear in the coming pruning. I believe there used to be a "delete" command via `foo.tiddlyspot.com/controlpanel` but this url doesn't seem to be accessible anymore. 

To be clear: I know their usernames+passwords so I was expecting it to behave like it did a few years ago. OR do I perhaps need to "take ownership" **via Tiddlyhost** first to delete them?

Thank you!

**Comment by simonbaird** [comment]
It's actually not possible to delete tiddlyspot sites currently, but it's on the roadmap.

**Comment by twMat** [comment]
> on the roadmap.

👍
