### ISSUE TITLE
Learn how to use the uglify to plugin to compress the tiddlywikicore js file

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#281]
Suggested by @telumire.

https://flibbles.github.io/tw5-uglify/uglified.html
https://flibbles.github.io/tw5-uglify/
https://github.com/Telumire/TW/raw/main/tiddlywikicore-5.2.3-uglified.js

**Comment by simonbaird** [comment]
See also #171.

**Comment by flibbles** [comment]
If you have uglify installed on your node server, any files you generate or servers you host should automatically create compressed content.

**Comment by flibbles** [comment]
```
node tiddlywiki.js +plugins/flibbles/uglify editions/empty --output corejs --render '$:/core/templates/tiddlywiki5.js' '[[tiddlywikicore-]addsuffix<version>addsuffix[.js]]' 'text/plain'
```
That should be it, assuming you've got uglify on your tiddlywiki plugin path.

**Comment by flibbles** [comment]
Or if you use editins/empty-with-uglify, then you could just add uglify to the list of plugins in the tiddlywiki.info file in that directory. Then that second command you listed would work fine. Super easy.

**Comment by simonbaird** [comment]
Thanks!

**Comment by simonbaird** [comment]
Here's what I have so far. It's close but not quite there:
```
  export TIDDLYWIKI_PLUGIN_PATH=../tw5-uglify && node tiddlywiki.js +plugins/plugins/uglify editions/empty \
    --output output/external-core \                                                                                                                                            
    --render '$:/core/templates/tiddlywiki5.js' '[[tiddlywikicore-]addsuffix<version>addsuffix[.min.js]]' 'text/plain' \
    --rendertiddler '$:/core/save/offline-external-js' 'index.html' 'text/plain'
```

It does uglify the contents of tiddlywikicore-5.2.3.min.js , but not the contents of the `$:/core` plugin tiddler which shows up like this:
```
$tw.preloadTiddlerArray([{"title":"$:/core","name":"Core" ... very long json...
```

So the trick would be to somehow uglify the core plugin before its content gets inserted into the tiddlywikicore.json.

**Comment by flibbles** [comment]
All right, the fault here is not with you. You're doing everything right.

The offline-external-js template is rendering core using the `jsontiddlers` macro, which is different from the `jsontiddler` widget which I thought all the exporting templates used. It slipped me by.

I'll have to push a fix for this. Shouldn't be hard, but probably won't be able to get to it for a couple days. Just know that the command you've written should work fine once a fixed version of uglify is available.

**Comment by simonbaird** [comment]
Ack, no worries and thanks again for the help.

**Comment by flibbles** [comment]
A new version of Uglify (1.5.5) is pushed where your command should work.

**Comment by simonbaird** [comment]
Works nicely. Thanks!
