### ISSUE TITLE
Use a more reliable host for external core js hosting

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#284]
Could be a real CDN, or maybe even a GitHub raw content url is more dependable than Tiddlyhost itself.

**Comment by Telumire** [comment]
According to this SO post you shouldn't use GitHub raw as a CDN: https://stackoverflow.com/questions/5502540/should-github-be-used-as-a-cdn-for-javascript-libraries/5503156#5503156

However they say that GitHub page could be considered

**Comment by pmario** [comment]
As a user that doesn't want to "ping" a CDN 3rd party everytime I do open my wiki, I would prefer if no 3rd party is involved.

**Comment by simonbaird** [comment]
> a bit of magic code, that loads a relative core for my local setup and CDN like core for an online version

I think that's the idea for download behavior 2 in issue #283 .

I'd hesitate before making it the default behaviour though, since I expect many Tiddlyhost users would expect their downloaded TiddlyWiki to work immediately.

Another idea is to make it configurable, so maybe under advanced options there is a "Always use relative url for core js instead of CDN", but I can't see it being useful for the majority of Tiddlyhost's target audience.

Yet another idea: Maybe a redirect can work, so the url is relative but the file ends up being fetched from the CDN due to the redirect.

**Comment by pmario** [comment]
>I'd hesitate before making it the default behaviour though, since I expect many Tiddlyhost users would expect their downloaded TiddlyWiki to work immediately.

If a download from Tiddlyhost creates a single-file wiki I think that would be perfect.

**Comment by Telumire** [comment]
I dont know if it could be useful or not but there is a way to convert a zip file to a single file html : https://github.com/gildas-lormeau/SingleFileZ

Maybe it would be possible using this technology to bundle the external javascript with the html. Of course it would be better to be able to generate a "standard" tiddlywiki upon hitting the save button but maybe this approach would be easier to implement ?

**Comment by pmario** [comment]
>the advantage being that no modification of the html / js code is required ?

The existing save mechanism should work. IMO the only thing needed is a new button.

**Comment by simonbaird** [comment]
@pmario I added a couple of new "download" options for external core TiddlyWikis, currently called 'Download with local core source' and 'Download core js'. Do they work like you'd expect them to?

**Comment by pmario** [comment]
I did test the download the overview page. All 3 options seem to download the same file with a link to the external core. So the HTML file is small. .. Did I miss something?

![image](https://user-images.githubusercontent.com/374655/207097601-28f70d79-4ffa-4fbd-8560-7e8218888613.png)

**Comment by pmario** [comment]
Ahh I see:  May be the first Download link should contain an info, that it needs internet connection

![image](https://user-images.githubusercontent.com/374655/207098988-6d3af0ab-5809-4d99-b0fb-6a664063db29.png)

**Comment by simonbaird** [comment]
Good idea, maybe "Download with core loaded from internet" will be enough to indicate the difference.

**Comment by Telumire** [comment]
Maybe "Download with online core source"

**Comment by simonbaird** [comment]
This isn't a high priority currently so perhaps it could be closed. There's some advantage in not introducing the extra complexity, even if the average uptime on "tiddlyhost.com" is less than a CDN would be.

**Comment by simonbaird** [comment]
https://www.jsdelivr.com/ maybe
