### ISSUE TITLE
How's a visitor to download?

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#302]
I don't know if it is solvable but it is nonetheless an issue:

How is a visitor to save/download a copy of the Tiddlyhosted TW? The browser command doesn't work but clicking the TW save button also doesn't work. For myself, you taught me the trick to add `/download` to the URL, but a visitor can't be expected to know or use this.

...or is this a TW issue, not a TH issue?

**Comment by simonbaird** [comment]
If you (the TiddlyWiki author) want to make it easy for someone to download, there are several ways you can provide a download link. See [here](https://simon.tiddlyhost.com/#Download%20button%20demo:%5B%5BDownload%20button%20demo%5D%5D%20%5B%5BDownload%20link%20demo%5D%5D%20%5B%5BDownload%20full%20wiki%20button%20demo%5D%5D) for a few examples.

I'm not sure what the idea solution is, but adding a download button would be a good starting point.

**Comment by simonbaird** [comment]
It might be possible to make it so the save button falls back to a download when the user is not logged in.

Thinking about this further: TiddlyWiki checks for the PUT capability right after loading. Tiddlyhost will generally respond to indicate that a put save is possible, but it doesn't do any check about whether the user really can save, i.e. it doesn't check the user is logged in and owns the site. Perhaps it could do that check, and only respond in the affirmative if the save is truly possible. Then the save button might automatically fall back to a download.

I think the downside with that is that it would be confusing for a less experienced Tiddlyhost user who doesn't understand why the why the save stopped working. In this scenario they are not going to get any indication that they need to log in again to restore the expected functionality, which could be frustrating and confusing. (Maybe as a compromise for those users, it could be an advanced option, e.g. "Save should fall back to a download when user is not logged in or doesn't own the site".)

**Comment by simonbaird** [comment]
See also #122 which I realized is pretty much the same topic.

**Comment by simonbaird** [comment]
Closing this one since I don't think this is a problem Tiddlyhost wants to solve.

FWIW I'm maintaining a download button in MPTW5 now, see [here](https://mptw5x.tiddlyhost.com/#%24%3A%2FMptw5%2FDownloadButton).
