### ISSUE TITLE
Support for Libravatar

### ISSUE THREAD

**Issue by accordioncitylights** [simonbaird/tiddlyhost#303]
Will TiddlyHost support [Libravatar](https://www.libravatar.org) in the future? I use it in lieu of Gravatar.

**Comment by simonbaird** [comment]
Good idea.

**Comment by simonbaird** [comment]
Libravatar support is added. Click manage account in the user menu to find it.

**Comment by accordioncitylights** [comment]
It works! Thank you very much!
