### ISSUE TITLE
Restore tiddlyhost site? bookmarklets

### ISSUE THREAD

**Issue by AnthonyMuscio** [simonbaird/tiddlyhost#308]
Hi,

I was upgrading my site https://bookmarklets.tiddlyhost.com/ and something went wrong and despite it seeming to be an appropriate size I can't see the original content. I am a paid user but wondering if there is yet a way to restore it to its previous condition? before any changes today.

Tony

**Comment by simonbaird** [comment]
You can do this yourself via the "Site history" page, which is available to subscribed users.

* Find the "bookmarklets" site in https://tiddlyhost.com/sites .
* Click the "..." button under "Actions" to open the menu, then click the "Save history" menu option.
* To restore the previous version, find the newest older version and click the "..." button under "Actions" to open the menu, then click the "Restore as current version" menu option.

**Comment by simonbaird** [comment]
Let me know if you have any problems.

**Comment by AnthonyMuscio** [comment]
Thanks, I see now how to read that menu option "save history", in a way it may read better as "View 'Save History'". Thanks for your help
