### ISSUE TITLE
tiddlywikicore-5.3.2.js contains wrong tiddlers 

### ISSUE THREAD

**Issue by buggyj** [simonbaird/tiddlyhost#324]
I create a new external core wiki on tiddlyhost and dragged $:/core/ui/SideBar/Open from [tiddlywiki.com](http://tiddlywiki.com) on to https://testincludecore.tiddlyhost.com/ - imported it then compared - they are different - 
![](https://talk.tiddlywiki.org/uploads/default/original/2X/f/f9241f34cfd2bf96c4c44fc9fecb4f630a4f5e41.png)

**Comment by simonbaird** [comment]
My first thought is that might relalted to the use of the [uglify](https://github.com/flibbles/tw5-uglify) plugin on the external core js file use by Tiddlyhost, but there are some substantial looking changes in that diff, so I'm not sure.

Will take a closer look soon.

@flibbles @pmario any suggestions?

**Comment by simonbaird** [comment]
I'm building the external core edition like this:

```
git checkout v5.3.2                                                                                             

node tiddlywiki.js editions/empty \                                          
    --output ./output/external-core \                             
    --rendertiddler '$:/core/save/offline-external-js' 'empty.html' 'text/plain'

node tiddlywiki.js  editions/empty \                                         
    --output ./output/external-core \                                                                                                            
    --render '$:/core/templates/tiddlywiki5.js' '[[tiddlywikicore-]addsuffix<version>addsuffix[.min.js]]' 'text/plain'
```

**Comment by simonbaird** [comment]
Re the uglify theory, I got the same result with or without the uglify plugin, so I don't think that is the cause.

Perhaps the `\whitespace trim` causes some whitespace to be stripped out when the render happens...?

**Comment by pmario** [comment]
IMO they are not wrong. They are uglified. It looks OK to me.

**Comment by flibbles** [comment]
Bear in mind that there is a [slight known issue using Uglify with 5.3.2](https://github.com/flibbles/tw5-uglify/issues/12). It should be resolved after the TiddlyWiki core PR https://github.com/Jermolene/TiddlyWiki5/pull/7895 is merged.

**Comment by flibbles** [comment]
To elaborate here, there were changes to the way whitespace after pragma is handled by the wikiparser. It's now preserved except in cases when `\whitespace trim` is present. So when Uglify removes whitespace trim and manually removes the whitespace instead, there's now a newline introduced preceding the body. This is causing some very subtle problems, and looking at the diff above, that tiddler would get that introduced newline.

**Comment by buggyj** [comment]
when I do build I do not see this error:

git clone https://github.com/Jermolene/TiddlyWiki5 .
 git checkout v5.3.2                                    
  node tiddlywiki.js editions/empty       --output ./output/external-core     --rendertiddler '$:/core/save/offline-external-js' 'empty.html' 'text/plain'
node tiddlywiki.js  editions/empty   --output ./output/external-core  --render '$:/core/templates/tiddlywiki5.js' '[[tiddlywikicore-]addsuffix<version>addsuffix[.min.js]]' 'text/plain'

I had to rename 'tiddlywikicore-5.3.2.min.js' to 'tiddlywikicore-5.3.2.js'

**Comment by pmario** [comment]
Just to be sure you've seen this one: https://github.com/Jermolene/TiddlyWiki5/issues/7904#issuecomment-1866038014

**Comment by simonbaird** [comment]
>  I got the same result with or without the uglify plugin

I think I was mistaken. Now it looks like the problem goes away if the uglify plugin is not used, as @buggyj found.

**Comment by flibbles** [comment]
The problem will go away with v5.3.3, but I'll also be pushing a new Uglify version soon which will make an exception for v5.3.2 anyway.

**Comment by simonbaird** [comment]
In case anyone is wondering what the plan is: I'm going to assume this is not causing any major problems on Tiddlyhost currently, and just wait for the upcoming fixes to land.

If you are seeing any problem with the external core TW 5.3.2 on Tiddlyhost let me know - I could build and push a non-uglified core js if needed.

**Comment by flibbles** [comment]
I've released Uglify v1.8.0 which has full support for Tiddlywiki 5.3.2, including support for the anomalous behavior that Tiddlywiki introduced.

I recommend migrating to Tiddlywiki 5.3.3 as soon as it releases because the workaround for the core bug means Uglify has to forgo some compression it'd ordinarily want to do.

**Comment by simonbaird** [comment]
Thanks - Pushing a release to Tiddlyhost now.

**Comment by simonbaird** [comment]
Ps, it is perhaps surprising for Tiddlyhost users to notice that tiddler content is different when using an external core TiddlyWiki on Tiddlyhost (due to the uglify). Is there an option for uglify so it compresses the javascript but leaves the content of the shadow tiddlers uncompressed?

**Comment by buggyj** [comment]
seems to be fixed in  v5.3.3

**Comment by flibbles** [comment]
> Is there an option for uglify so it compresses the javascript but leaves the content of the shadow tiddlers uncompressed?

Yes. The documentation on how to do that through a NodeJS compile [is here](https://flibbles.github.io/tw5-uglify/#Configuration). It's the last one described.

If you're using the wizard (which I don't think you are), it's just a matter of unchecking the `text/vnd.tiddlywiki` box.

**Comment by flibbles** [comment]
But actually, now that I think about it, you probably just want to use the `"--uglify", "text/vnd.tiddlywiki", "no"` build options.
