### ISSUE TITLE
Lost tiddly site

### ISSUE THREAD

**Issue by selouti** [simonbaird/tiddlyhost#329]
Hi, I lost https://thoughts-from-the-other-side.tiddlyhost.com/ . It now only shows the startup page for a new site without any sidebar.
Version: [1.4.18-5ea426a](https://tiddlyhost.com/about)
Built: 8 days ago
© 2021-2024 Simon Baird

**Comment by simonbaird** [comment]
Hi @selouti, I'll take a look soon and see if we can recover your site.

**Comment by selouti** [comment]
Hi, Its a bit better. I now get a very narrow sidebar and I see my content there but I cannot resize the sidebar (Chrome). 
(I have standalone and another new git tiddly that show the sidebar's 50/50 with the content boxes).

**Comment by simonbaird** [comment]
There are some settings under "Control Panel", "Appearance", "Theme Tweaks".

![image](https://github.com/simonbaird/tiddlyhost/assets/17822/e00e85c4-9d6f-4f80-9936-a33a8887c115)

I think some of those are set too large so the layout is broken. Try setting those back to the default values shown above, especially the story right . I expect "story width" and "story right" are the main problem.

**Comment by selouti** [comment]
Hi, Thanks. It had 2000 and whenever you edit either of these values the sidebar sizes down to almost nothing. I ended up with 1500 (both). Which works for me. Thanks.
