### ISSUE TITLE
TiddlyWiki Lost Data Help

### ISSUE THREAD

**Issue by om-nash** [simonbaird/tiddlyhost#331]
Hello, 

I am a new user of TiddlyHost. I created a private web-based TiddlyWiki site, and worked on it for about two days straight. After I manually refreshed my browser, I got an access denied error. I went back to the main site and signed in, and all of my data had disappeared!! Everything, completely wiped out. I checked the backup versions, and they don't contain anything either. Please tell me there's a way to recover two days of my life.

**Comment by simonbaird** [comment]
Are you still having this problem?

I'm not sure if we're talking about the same site, but I can see one belonging to (I assume) your account that appears to be working fine. It has 100 different saved versions in its history.

Do you see one site listed at https://tiddlyhost.com/sites when you're signed in currently?

**Comment by om-nash** [comment]
Hi. I'm no longer having the issue. I think I may have initially done
something like change the slug for the site name while the wiki was loaded,
which prevented it from saving. That's a harsh way for a newbie to find out
that the software goes fast and has no seatbelts. It would be helpful for
new users to be strictly prevented from doing something like that. It would
also be helpful if there was a prominent warning if auto save is not
enabled. Thankfully, I was able to recreate most of my work, but losing it
stung. Thanks for your help!
