### ISSUE TITLE
confetti! v5.3.4

### ISSUE THREAD

**Issue by stevesunypoly** [simonbaird/tiddlyhost#332]
Hi, Big fan of tiddlyhost, and just today, finally, became a subscriber....

I noticed in https://confetti.tiddlyhost.com/ (into which I uploaded 5.3.4 pre-release and dragged confetti plugin) that we get a javascript error...

**Comment by simonbaird** [comment]
I'll take a look. Can I assume it works otherwise, i.e if you're not using Tiddlyhost, then the plugin works fine?

**Comment by simonbaird** [comment]
The error is this:
```
TypeError: Cannot read properties of undefined (reading 'launch')
    at ConfettiWidget.render (confetti-widget.js:44:23)
```

**Comment by stevesunypoly** [comment]
I think so but didn’t test it. It was just a kind of joke to respond to a post in talk.tiddly that I opened the 10000th topic



//steve.

——-
Steve Schneider
SUNY Polytechnic Institute

________________________________

**Comment by simonbaird** [comment]
That [line of code|https://github.com/Jermolene/TiddlyWiki5/blob/5c63262feb538c81bb644b91e287305b523761cc/plugins/tiddlywiki/confetti/confetti-widget.js#L44] suggests there are two plugins, "confetti-manager" and "confetti-widget", so perhaps you need to bring in the "confetti-manager" plugin also.

**Comment by stevesunypoly** [comment]
Oh so sorry to waste your time!

I love tiddlyhost and (outside your ticket system) we should discuss the possibility that my bookstore vendor could put a semester subscription to tiddlyhost online as required course software. I teach about 15-20 students a year who get tiddlyhost accounts.

//steve.

——-
Steve Schneider
SUNY Polytechnic Institute

________________________________

**Comment by simonbaird** [comment]
No worries, and feel free to shoot me an email.

Ps, thanks for becoming a subscriber, much appreciated.
