### ISSUE TITLE
[418 Invalid TiddlyWiki] Tiddlyhost report tiddlywiki as invalid when attempting to load script with $:/tags/RawMarkupWikified/TopHead

### ISSUE THREAD

**Issue by DesignThinkerer** [simonbaird/tiddlyhost#336]
I was trying to use the mermaidjs library to render mermaidjs diagram in my wiki. In order to load the mermaidjs code, I used the tag RawMarkupWikified, and this caused tiddlyhost to make the wiki unavailable (I thankfully did a backup before attempting to do this so I did not lose anything).

Steps to reproduce:

Create a tiddler with the tag `$:/tags/RawMarkupWikified/TopHead`

And the content

```js
<script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@9/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true});
</script>
```

On the next page load, this error is displayed:

![image](https://github.com/user-attachments/assets/5205554c-839d-4cc7-9177-867056f64343)

For now I'm using a macro as a workaround:

```
\define mermaid(code)
<iframe style="border:unset;width:100%" srcdoc="""
<style>
svg{position:fixed;inset:0;}
</style><script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@9/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true});
</script>
<pre class="mermaid">$code$</pre>
"""/>
\end
```

**Comment by simonbaird** [comment]
With the `$:/tags/RawMarkupWikified/TopHead` the content is wikified before being injected, so you end up with this in the TW file:

```
...
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<!--~~ Raw markup for the top of the head section ~~-->

    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@9/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true});

<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
<meta name="application-name" content="TiddlyWiki" />
...
```

If you use the `$:/tags/RawMarkup` then it works more like you want it to, but it will be inserted at the bottom of the `<head>`  element not the top.

```
...
<!--~~ Raw markup ~~-->

<script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@9/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true});
</script>

</head>
...
```

So I suggest you use `$:/tags/RawMarkup`. I'm not sure how to insert unwikified content at the top of the `<head>` element, but perhaps there is a way.

There might also be a way to have the wikified content have the required <script> tags. Let me experiment with that.

**Comment by simonbaird** [comment]
I thought maybe using `{{{` and `}}}` around the tiddler content would help, since the wikified output would be the raw text, but for some reason it produces this:

```
...
<head>
<scripttype>importmermaidfromhttps://cdn.jsdelivr.net/npm/mermaid@9/dist/mermaid.esm.min.mjs;mermaid.initialize({startOnLoad:true});
...
```

Maybe a TiddlyWiki expert could help explain why it's doing that.

Anyway, my suggestion is to use the `$:/tags/RawMarkup` tag, not `$:/tags/RawMarkupWikified/TopHead`.

**Comment by saqimtiaz** [comment]
> Create a tiddler with the tag `$:/tags/RawMarkupWikified/TopHead`

Try this:

```
`<script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@9/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true});
</script>`

```

Note the backticks that should prevent the script tag from getting wikified.

**Comment by DesignThinkerer** [comment]
> > Create a tiddler with the tag `$:/tags/RawMarkupWikified/TopHead`
> 
> Try this:
> 
> ```
> `<script type="module">
>     import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@9/dist/mermaid.esm.min.mjs';
>     mermaid.initialize({ startOnLoad: true});
> </script>`
> ```
> 
> Note the backticks that should prevent the script tag from getting wikified.

This seem to work ! 

https://louder-haulage-15.tiddlyhost.com/#Demo:Demo%20%5B%5BNew%20Tiddler%5D%5D%20GettingStarted

There is another issue : it will only render mermaid js graph for tiddlers that are in the story at startup, but I'm guessing that this is due to the rendering engine of tiddlywiki and not a bug. I should be able to solve this bu creating a custom widget, probably.

Thanks @simonbaird and @saqimtiaz !

**Comment by saqimtiaz** [comment]
@DesignThinkerer there is an existing mermaid plugin that you might be able to make use of: https://talk.tiddlywiki.org/t/another-mermaid-widget-mermaid-widget/8998

**Comment by simonbaird** [comment]
> Note the backticks that should prevent the script tag from getting wikified.

Ah, thanks @saqimtiaz, that's what I was looking for.
