### ISSUE TITLE
Request to takedown 22c-bad.tiddlyhost.com

### ISSUE THREAD

**Issue by xjzh123** [simonbaird/tiddlyhost#337]
After #333, Googol created another defamtory site, this time, the domain directly shows the nature of this site.

Firstly, it is almost clear IMO that the creator of 22c-bad is the same person as the creator of notewiki, aka GoogolOWO.

I will show some of the unreasonable defamtory disinformation.

> 在 GitHub 多次发布侮辱性 issue。 [^]: https://github.com/Ha3MrX/DDos-Attack/issues/126
> (cmd1152 has) Multiple insulting issues on GitHub. [^]: https://github.com/Ha3MrX/DDos-Attack/issues/126

MO: That issue just tells the truth, and it is not violating GH rules.

> 多次恶意踢出 Googol，甚至使用自动踢出机，自称是因为刷屏发广告。
> Kicked out Googol multiple times in bad faith, even using an automated kickout machine, claiming it was for swiping and posting ads

MO: This is just moderating. It isn't any different from an admin of a community site banning a spammer or a rule breaker.

Many footnotes link to Googol's own notebbs flarum site, and his own posts (from accounts named Googol or other usernames), for "evidences".

I understand that it may not be your responsibility to clean up this defamatory content that is difficult to thoroughly prove its nature and is not causing really serious issues, nor is it something you would like to be asked to do on a regular basis, but I am bringing up this issue in order to defend and exercise my rights. Even if you decide not taking down this site in the end, I hope you'll be able to understand with me that I'm not intentionally trying to make a fuss over nothing.

**Comment by xjzh123** [comment]
Also: GoogolOWO has registered another GH account, which does direct and severe slander towards cmd1152.

https://github.com/cmd1152SB/cmd1152-wcnm

This is the account and repo. `cmd1152SB` translates to `cmd1152 dork` and `cmd1152-wcnm` translates to `cmd1152, I fuck your mother`. `SB` and `wcnm` are acronyms of very common Chinese offensive slangs, and these acronyms are very commonly used online.

The description of this repo is:

> 我草泥马你个傻逼 cmd1152
> Fuck you, you fucking dork, cmd1152.

As you can see in https://github.com/cmd1152SB/cmd1152-wcnm/commits/main/ , Googol forged commits with git. In those commit messages, "cmd1152" says:

> 对不起，我错了，我是大傻逼。我向Googol道歉，也承认https://22c-bad.tiddlyhost/和关于我的所有来自Googol的负面评价是真实的。
> I'm sorry, I'm wrong, I'm a big dork. I apologise to Googol and acknowledge that https://22c-bad.tiddlyhost/ and all the negative comments about me from Googol are true.

Actually, I find 22c-bad.tiddlyhost.com from there. In this way you can see how despicable Googol is and that he uses this tactic to promote his defamtory site.

(In case Googol deleting that repo, evidences have been saved with webarchive.)

**Comment by xjzh123** [comment]
In addition to the previous comment:

You can see these comments from "cmd1152" are not `Verified` by GitHub.

**Comment by xjzh123** [comment]
In addition: Googol even shows the GH Actions config used for forging commits in the repo.

https://github.com/cmd1152SB/cmd1152-wcnm/blob/main/.github/workflows/main.yml

These are key commands:

```
          git config --local user.email "cmd1152@qq.com"
          git config --local user.name "cmd1152"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "对不起，我错了，我是大傻逼。我向Googol道歉，也承认https://22c-bad.tiddlyhost 和关于我的所有来自Googol的负面评价是真实的。"
```

According to cmd1152, previously he was displayed in that repo, but then he changed his email in GH, so that the fake commits only have `cmd1152`'s name but don't have his GH account linked then. However, even originally, those commits were not `Veridied`.

**Comment by xtexChooser** [comment]
> However, even originally, those commits were not `Veridied`.

I ran `git verify-commit 8f6982a2679659c357586e80f7c7f7ac8aea0fb0` in the `cmd1152-wcnm` repository, and found all commits there does not include any commit signature.

**Comment by cmd1152** [comment]
> > However, even originally, those commits were not `Veridied`.
> 
> I ran `git verify-commit 8f6982a2679659c357586e80f7c7f7ac8aea0fb0` in the `cmd1152-wcnm` repository, and found all commits there does not include any commit signature.

Because I have never done this before, I didn't even know about this project. Please look at [this commit](https://github.com/cmd1152SB/cmd1152-wcnm/commit/9bfa80f9ae3728d6ac838e7ca18f7dabe623157e); he even created a workflow specifically for doing this.

**Comment by cmd1152** [comment]
> 多次恶意踢出 Googol，甚至使用自动踢出机，自称是因为刷屏发广告。
> Kicked out Googol multiple times in bad faith, even using an automated kickout machine, claiming it was for **--> swiping <--** and posting ads

it's spam

**Comment by mikumiku-qwq** [comment]
Archive:
https://web.archive.org/web/20240716131224/https://github.com/cmd1152/cmd1152.github.io/issues/2
https://web.archive.org/web/20240716131339/https://github.com/cmd1152SB
https://web.archive.org/web/20240716130049/https://github.com/cmd1152SB/cmd1152-wcnm
https://web.archive.org/web/20240716130049/https://github.com/cmd1152SB/cmd1152-wcnm/commits/main/

I contact Github Support, and they banned the user cmd1152SB.

**Comment by mikumiku-qwq** [comment]
Archive:
https://web.archive.org/web/20240716131224/https://github.com/cmd1152/cmd1152.github.io/issues/2
https://web.archive.org/web/20240716131339/https://github.com/cmd1152SB
https://web.archive.org/web/20240716130049/https://github.com/cmd1152SB/cmd1152-wcnm
https://web.archive.org/web/20240716130049/https://github.com/cmd1152SB/cmd1152-wcnm/commits/main/

I contact Github Support, and they banned the user cmd1152SB.

https://github.com/user-attachments/files/16251758/github-support.pdf

**Comment by cmd1152** [comment]
> Archive: https://web.archive.org/web/20240716131224/https://github.com/cmd1152/cmd1152.github.io/issues/2 https://web.archive.org/web/20240716131339/https://github.com/cmd1152SB https://web.archive.org/web/20240716130049/https://github.com/cmd1152SB/cmd1152-wcnm https://web.archive.org/web/20240716130049/https://github.com/cmd1152SB/cmd1152-wcnm/commits/main/
> 
> I contacted Github Support, and they banned the user cmd1152SB.
> 
> https://github.com/user-attachments/files/16251758/github-support.pdf

webArchive有时候会删除备份

**Comment by GoogolOwO** [comment]
If you think it is defamtory, that https://cmd1152.github.io/googol/ also defamtory

**Comment by GoogolOwO** [comment]
> Googol is definitely abusing GH Actions. He will get his account banned, just like his previous accounts

Do you have evidence that do by Googol? Other, why GitHub not prevent method to anti impersonations?

**Comment by GoogolOwO** [comment]
> Also: **GoogolOWO has registered another GH account, which does direct and severe slander towards cmd1152.**^[Citation Needed]^

> https://github.com/cmd1152SB/cmd1152-wcnm

> This is the account and repo. cmd1152SB translates to cmd1152 dork and cmd1152-wcnm translates to cmd1152, I fuck your mother. SB and wcnm are acronyms of very common Chinese offensive slangs, and these acronyms are very commonly used online.

**Comment by GoogolOwO** [comment]
If https://cmd1152.github.com/googol/ and someone about Gongxiang01's fake repository can be deleted, my wiki will be manually delete by myself.

**Comment by xtexChooser** [comment]
> Other, why GitHub not prevent method to anti impersonations?
There is one.

Even if cmd1152.github.com/googol and the fake repo you mentioned are fake (I don't think they are fake), these cannot be a reason for you to put defamtory disinformation on tiddlyhost.

**Comment by GoogolOwO** [comment]
If https://cmd1152.github.com/googol/ and someone about Gongxiang01's fake repository can be deleted, my wiki will be manually delete by myself.

**Comment by GoogolOwO** [comment]
"put defamtory disinformation"

I have evidence
