### ISSUE TITLE
Make it possible to open static TWs

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#338]
I just did an experiment which failed, which was to upload a static TW (i.e a file exported from TW). It seems the upload itself worked well (it is listed along with the other wikis) but attempting to **open** it gives:

```
418 Invalid TiddlyWiki
This site does not appear to be a valid TiddlyWiki.
```

What qualifies as a "valiid TiddlyWiki"? I'm hoping it would be possible to open static TW's.

(Do you need more details from me about *exactly* what I did?)

Thank you Simon!

**Comment by simonbaird** [comment]
Do you mean the file you get when you click "Export All" and "Static HTML"?

**Comment by twMat** [comment]
Well, in my case not all tiddlers, just one: "Export tiddler" and "Static HTML".

**Comment by simonbaird** [comment]
I'd say this is as intended. Tiddlyhost is not supposed to be a general purpose file host, so uploading static html is not supposed to work. Does that make sense? For hosting static html GitHub pages is a good a free option.

**Comment by twMat** [comment]
Just FYI, if you're curious, the plugin is now [officially](https://talk.tiddlywiki.org/t/presenting-static-finally-share-tids-with-normal-people-for-real/10262) released :-)

Apropos the OP; One idea might be to consider uploads of static wikis as a perk for people who *pay* for using Tiddlyhost.

Regardless, thank you for the fantastic Tiddlyhost service.!

**Comment by simonbaird** [comment]
Nice work! Exporting large amounts of content as static seems interesting. I'll confess I'm not fully understanding the motivation, since I expect a TiddlyWiki itself should be a good way to publish and consume content created in TiddlyWiki, but I guess you're finding that the TiddlyWiki native navigation and story view is difficult for some people to get their head around, is that right?

**Comment by twMat** [comment]
> I'm not fully understanding the motivation

Well, TiddlyWikis wonderful but quirky navigation is only a very minor reason:

I want to share stuff in my real "work TWs" with others (colleagues, family etc) but these wikis have loads of stuff that I do *not* want to share. So what are the options?

* Create separarate/shareable wikis and *manually* copy the tids I want to share = Totally impracitcal
* Use TWs native export function. = Risks outputting an overwhelmingly long row of tiddlers.

So, the idea is instead to use the main wiki as a publisher and organize the static tiddlers a more palpable format.

BUT, maybe the node-js version of TW has these things solved already, to share filtered sets of tiddlers? I have very limited experience from the node-js version. (I did love TiddlySpace when it was around, based on TiddlyWeb, that made creating new TWs out of a subset of tiddlers very simple if I recall.)

**Comment by simonbaird** [comment]
Right, conveniently sharing a subset of your content is a nice feature. :bulb: !
