### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#342]
In recent weeks Tiddlyhost has been much slower than it ought to be. I don't know why, but I want to figure it out and fix it.

**Comment by simonbaird** [comment]
Right now every page seems to take 8 or 10 seconds to load, even if it's a page that should be just rendering some html.

**Comment by Jenny3107** [comment]
Hello, 
I can confirm that since about 45 minutes, saving changes on a Tiddly takes about 80 seconds on Tiddlyhost.
Good luck to fix it!

**Comment by simonbaird** [comment]
Not sure if it's impacting performance, but I'm seeing Tiddlyhost responding with a `406 Not Acceptable` to a HEAD request with `Accept` header set as `*/*;charset=UTF-8`.

**Comment by Jenny3107** [comment]
Would you like me to open a new issue for the latency problem on TiddlyHost?

**Comment by simonbaird** [comment]
I think it's probably the same root cause, so this single issue should be enough.

**Comment by simonbaird** [comment]
I'm not certain but I think the the change in commit b8154dfdaa560bd8883e957e35612aad88314e8d introduced a performance regression. I've reverted it, and it looks like that did drop the the load average and the amount of CPU showing in top for the ruby process. At this stage I'm not sure how much impact that will have on the overall problem.

**Comment by simonbaird** [comment]
https://github.com/tmm1/rbtrace might be useful.

**Comment by simonbaird** [comment]
It's easy to observe with:
```
time curl -s https://tiddlyhost.com/ |tail -5
```
The real time should be under 0.2 seconds, and it often it is, but at other times it spikes up to 9 or 10 seconds for unknown reasons.

**Comment by fu-sen** [comment]
Hi, I’ve been noticing something odd lately which is why I’ve landed on this.
Saving a wiki doesn't work, maybe it's related to this issue. If not, please separate the issue.

**Comment by simonbaird** [comment]
@fu-sen Saving should be working now as far as I can tell. Can you give me more details about how it's not working for you?

**Comment by fu-sen** [comment]
I am trying to update https://balloonvendor.tiddlyhost.com/, but even when I save the Wiki, it times out after a few minutes.
and the Updated time will not change in the Your sites list.
I think this is because I live in Japan, so I'm far away from the server, and also because this Wiki is relatively large in size.

My Feather Wiki is small in size and the saving works.

**Comment by simonbaird** [comment]
This is good:
![image](https://github.com/user-attachments/assets/b50a83e3-f6e1-4359-8bf9-e7eeb72be34c)

The drop in CPU local at around 5:30pm is when the `robots.txt` was deployed, see 64bc75f41a48cb74849aac1c09abc407ad9a380e.

Not sure about the large spike at 10pm, but let's hope it's not a regular thing.

**Comment by simonbaird** [comment]
Let's close this. We can open additional issues for performance as needed. There are still some users experiencing saving problems, see #345, but the original slowness due to high CPU load caused by webcrawlers should be resolved.

**Comment by simonbaird** [comment]
CPU load average looking alright:

![image](https://github.com/user-attachments/assets/99e77946-de68-4494-ae7d-101ccbb5facc)
