### ISSUE TITLE
Request for "Duplicate wiki" button on settings page

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#57]
Would be neat with a simple "Duplicate wiki" button next to each listed wiki on the *Your sites* page.

A particularly valuable use case is to set up ones own "default wikis" that has ones favourite plugins and quirks already set up, so that a one doesn't have to always install and tweak things for each new wiki.

Thanks to the feature to rename wikis (great!), I guess the copies of a wiki could get the name name as the original with a suffixing count number (as also used when *New Tiddler 1*, etc). I do not like e.g Google Drives way to *prefix* copies with "*Copy of*" because the alphabetic listing then separates the copy form the original making it difficult to locate among many files.

**Comment by simonbaird** [comment]
Great idea, and not too hard to implement. Thanks for the suggestion!

**Comment by simonbaird** [comment]
#198 is fresher and I think the same feature, so let's close this one.
