### ISSUE TITLE
Site backups and "restore previous version" functionality

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#74]
As I'm now beginning to use TH more seriously to develop stuff, I need a backup feature like in TS. Maybe I'm just not seeing something in front of my nose? IMO the most suitable place for it would be Your sites page or inside the Settings.

**Comment by simonbaird** [comment]
IIUC you're imagining a list of older versions of your site, and being able to restore an older version.

It's a reasonable idea, but it does (presumably) multiply the storage costs per site by the number of older versions that are saved.

**Comment by twMat** [comment]
Well it doesn't have to be like in TS with a full history since origin, but I've already experienced need for *some* backup. For example, currently if you get a RSOD then there's risk you've saved the bug. But it doesn't even have to get that problematic for it to cause frustration when not being able to return to something.

Some ideas:

* The user actively has to activate the backup feature.
* Backups only for the last n versions.
* Backups auto-erase after n time.

**Comment by twMat** [comment]
Case in point: I just messed up a wiki so it directly throws a RSOE. By mere luck I rememberd a searchable term in the last tiddler that I fiddled with, i.e likely the corrupt one, so I downloaded a local copy and edited in texteditor. However, it can't be uploaded becasue the original doesn't load so there's nothing to drop my local copy on. So instead I would have to delete the TH instance and recreate it empty so I can dropy my local copy onto it. 

But just in case you want to peek at the corrupt one I will instead create a new TH instance and drop it there.
The corrupt one is at: https://ebno-uppg.tiddlyhost.com/ ...not that there's anything much to see there, but just in case something was not clear in my description.

**Comment by simonbaird** [comment]
FYI, upload support is coming soon, which gives you a chance to recover from this type of thing.

(Not that it discounts the usefulness of a "restore previous version" function.)

**Comment by simonbaird** [comment]
FYI @twMat upload support is live now, so you could try using it to fix your broken site.

**Comment by simonbaird** [comment]
@twMat Are you interested in testing this? I've enabled it for your account, (but not for everyone since I'm planning to make this feature for subscribed users only in the future.)

Look for a "Save history" option in the actions menu. It might not appear until you do a fresh save.

**Comment by twMat** [comment]
@simonbaird - cool! I'd love to test it but unless it is a quickie it'll have to be after christmas. Is that OK?

**Comment by simonbaird** [comment]
Done, mostly via d844c5658e32cc24b72b6b7e1cd8bb76446e6457 and 5fffa1c6df5ecebb4a2e660605a5fc2103f1ca11 .
