### ISSUE TITLE
[Critical bug] Saving in downloaded TW does not work

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#79]
To replicate

1. Download a TH hosted wiki from the *Your sites* page.
2. Open the tw and make some mod and click the regular circled tick to save.
3. ...nothing happens. 

I need to go into the TiddlySpot saving section in the Ctrlpanel and clear the Server URL field for local saving to work.

**Comment by simonbaird** [comment]
Ah, thanks. I think there should be a way to fix that, maybe by checking the document.location.
