### ISSUE TITLE
Accept donations via something other than PayPal

### ISSUE THREAD

**Issue by acarv** [simonbaird/tiddlyhost#85]
Hi Simon
Great work!
I would like to contribute with a donation but I have no PayPal (as they were not up to my expectations some years ago).
Do You have an alternative way? Simplest one would be bank transfer through a IBAN.

Best regards
André

**Comment by simonbaird** [comment]
Not sure about IBANs, but I could look into it. Is Venmo any better?

**Comment by acarv** [comment]
Plain bank transfer I think is the most universal and easy to use.

It would also be useful if we could make some kind of redirect from TiddlySpot like TiddlySpace did some years ago.

**Comment by simonbaird** [comment]
FYI there's a "Github Sponsors" link now, see https://tiddlyhost.com/donate .

**Comment by simonbaird** [comment]
Also buymeacoffee. There might a stripe option once the supscriptions are launced. Resolve this one.
