### ISSUE TITLE
TH down?

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#91]
Can't access TH for the past 20 minutes, possibly more.

**Comment by simonbaird** [comment]
I just noticed it too. I can't ping. Trying a restart of the dreamcompute instance.

**Comment by simonbaird** [comment]
Looks like we're back online now.

**Comment by simonbaird** [comment]
Thanks for the report.

**Comment by simonbaird** [comment]
I briefly looking in the logs but didn't find much. Would be good to know more about the root cause, but anyway I'll close this.

**Comment by simonbaird** [comment]
I did find #92 though, but probably not related to the outage.

**Comment by simonbaird** [comment]
No outage notices at https://www.dreamhoststatus.com/ this time.

**Comment by twMat** [comment]
Thanks.
