### ISSUE TITLE
external Backup via Cronjob

### ISSUE THREAD

**Issue by h4p4t3** [simonbaird/tiddlyhost#93]
Is it possible (or could it be possible) to trigger a recurring download of my TiddlyWiki e.g. via cron? I'm not sure how to pass the authentication ...

Greetings
Jens

**Comment by simonbaird** [comment]
Not sure, but I suspect it's possible with curl and a cookies file. I will see if I can come up with an example script.

**Comment by h4p4t3** [comment]
That would be fine. 

Using curl is obvious, but I am not sure how to hand the cookie file. I'm afraid it's not possible to use a cookie generated on another system and I would expect It's necessary to renew it from time to time.

If there is another way to perform a local, recurring backup, I would give it a try.

Thx

**Comment by simonbaird** [comment]
I got something working, see https://github.com/simonbaird/tiddlyhost/blob/main/examples/thost-downloader .

See if it works for you.

**Comment by h4p4t3** [comment]
This works out fine. Thank you!

I had another idea suggesting Two-factor Authentication for TiddlyHost, but I'm afraid this would ruin my backup-strategy. ;-)

**Comment by h4p4t3** [comment]
Hi there,

somehow the doesn't work anymore. But unfortunately I am not able to figure out why. Last download via cron was on September, 30th 0:10. CEST

**Comment by simonbaird** [comment]
Still working for me afaict. What happens - do you get an error message?

**Comment by h4p4t3** [comment]
So much for "never change a running system". After several attempts on my RasPi I discovered the script is working on my Ubuntu machine. 😳

It seems an update of the curl-package fixed my problems. Afterwards I got 42 messages "Download failed." from Cron Daemon. 🙄

Thank You anyway!
