### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by h4p4t3** [simonbaird/tiddlyhost#96]
Hi there,

I have created two sites and uploaded my own TiddlyWikis to replace them. Now I am not able to save, when I click the save button, a download is triggered. The settings in the TiddlyWikis (Saving -> TiddlySpot Saver) are the same as in an empty, new TiddlyWiki, in which saving works out fine.

**Comment by simonbaird** [comment]
I think probably you need steps 7, 8 & 9 from [this guide](https://github.com/simonbaird/tiddlyhost/wiki/Using-a-5.1.23-or-earlier-version-of-TiddlyWiki).

**Comment by h4p4t3** [comment]
Sorry. I'll promise to read carefully next time. O:-)

Thank you!

**Comment by simonbaird** [comment]
np :)
